export const sovereignConfig = Object.freeze({
  featureEnabled: false,
  tierKey: 'sovereign' as const,
  bossKey: 'LAST_BOSS' as const,
  initialThroneName: 'CAELUM',
  timezone: 'Asia/Bangkok' as const,
  humansPerMatch: 3,
  matchesPerCycle: 3,
  gamesPerMatch: 3,
  qualifierCount: 9,
  qualifiersPerPath: 3,
  minimumCompletedMatches: 10,
  bestMatchCount: 10,
  monthlyScoreByHumanRank: Object.freeze({ 1: 10, 2: 6, 3: 3 } as const),
  scoringOpenLocal: '00:00:01',
  scoringCloseLocal: '18:00:00',
  publishLocal: '20:00:00',
  confirmationDeadlineLocal: '23:59:59',
  standbyOpenLocal: '19:45:00',
  checkInOpenLocal: '20:00:00',
  checkInCloseLocal: '20:05:00',
  matchStartLocal: '20:05:30',
  reserveOfferDurationMs: 6 * 60 * 60 * 1_000,
  standbyReconnectGraceMs: 20_000,
  spectatorReconnectGraceMs: 20_000,
  spectatorDelayMs: 30_000,
  maxSpectatorsPerMatch: 100,
  publicFeedRetentionDays: 90,
  immediateStandbyPromotion: true,
  ascendantMinimumToken: 600_000,
  ascendantPassDurationMs: 30 * 24 * 60 * 60 * 1_000,
  ascendantRequiresHighNoble: true,
  ascendantRequiresMonarchSlayer: false,
  ascendantOncePerAccount: true,
  targetBossDefenseRate: 0.75,
})

export const sovereignEconomyConfig = Object.freeze({
  crestPerCrown: 12,
  anteCrest: Object.freeze({ pile1: 9, pile2: 9, pile3: 18 }),
  auctionBidOptionsCrest: Object.freeze([0, 9, 18, 27, 36] as const),
  callCostCrest: 9,
  entryFeeCrest: 36,
  minimumVariableMatchCostCrest: 108,
  maximumVariableMatchCostCrest: 324,
  requiredReservationCrest: 360,
  rakeRate: 0,
  spendOrder: Object.freeze(['EARNED', 'PURCHASED'] as const),
  unclaimedBattleRewardsDestination: 'CROWN_SINK' as const,
})
