import { buildTierDLeaderboardSnapshot, trophyEligibleForFinalRank, type TierDLeaderboardRow } from '../../src/game/tierDLeaderboard'
const row = (id: string, level = 25, points = 10, at = '2026-01-01T00:00:00Z'): TierDLeaderboardRow => ({ userId: id, displayName: `Player ${id}`, avatarUrl: null, leagueId: 'tier-d-league-1', currentLevel: level, leaguePoints: points, rankedEligible: true, updatedAt: at })
describe('Tier D personalized leaderboard', () => {
  test('Relax has no board', () => expect(buildTierDLeaderboardSnapshot([{ ...row('me'), rankedEligible: false }], 'me', { minimumEligibleMembers: 1, contextTarget: 30, maxDisplayed: 20 }).enabled).toBe(false))
  test('early-launch gate exposes disabled only', () => { const result = buildTierDLeaderboardSnapshot([row('me'), row('other')], 'me'); expect(result).toEqual({ enabled: false, entries: [], currentUser: { rank: null, leaguePoints: 10 }, previousDisplayedRank: null }) })
  test('personalized nearby context returns at most Top 20 and no population field', () => { const rows = Array.from({ length: 35 }, (_, i) => row(`u${i}`, 21 + i, i)); const result = buildTierDLeaderboardSnapshot(rows, 'u10', { minimumEligibleMembers: 1, contextTarget: 30, maxDisplayed: 20 }); expect(result.enabled).toBe(true); expect(result.entries).toHaveLength(20); expect(result).not.toHaveProperty('population') })
  test('different nearby players receive distinct snapshots', () => { const rows = Array.from({ length: 31 }, (_, i) => row(`u${i}`, 21 + i, i)); const a = buildTierDLeaderboardSnapshot(rows, 'u1', { minimumEligibleMembers: 1, contextTarget: 10, maxDisplayed: 20 }); const b = buildTierDLeaderboardSnapshot(rows, 'u29', { minimumEligibleMembers: 1, contextTarget: 10, maxDisplayed: 20 }); expect(a.entries.map(x => x.userId)).not.toEqual(b.entries.map(x => x.userId)) })
  test('ties use deterministic update then user-id order', () => { const result = buildTierDLeaderboardSnapshot([row('b', 30, 10), row('a', 30, 10)], 'a', { minimumEligibleMembers: 1, contextTarget: 30, maxDisplayed: 20 }); expect(result.entries.map(x => x.userId)).toEqual(['a', 'b']) })
  test.each([[1, true], [2, true], [3, true], [4, false]])('final rank %i trophy eligibility is %s', (rank, eligible) => expect(trophyEligibleForFinalRank(rank)).toBe(eligible))
})
