import { buildTierDLeaderboardSnapshot, trophyEligibleForFinalRank, type TierDLeaderboardRow } from '../../src/game/tierDLeaderboard'
const row = (id: string, level = 25, points = 10, at = '2026-01-01T00:00:00Z'): TierDLeaderboardRow => ({ userId: id, displayName: `Player ${id}`, avatarUrl: null, leagueId: 'tier-d-league-1', currentLevel: level, leaguePoints: points, rankedEligible: true, updatedAt: at })
describe('Tier D personalized leaderboard', () => {
  test('Relax has no board', () => expect(buildTierDLeaderboardSnapshot([{ ...row('me'), rankedEligible: false }], 'me', { minimumEligibleMembers: 1, contextTarget: 30, maxDisplayed: 20 }).enabled).toBe(false))
  test('the first ten Levels of every League are a non-ranked break', () => {
    expect(buildTierDLeaderboardSnapshot([row('me', 10, 125)], 'me').enabled).toBe(false)
    expect(buildTierDLeaderboardSnapshot([row('me', 11, 125)], 'me').enabled).toBe(true)
  })
  test('sparse launch board is padded to 20 and remains ranked by cumulative points', () => { const result = buildTierDLeaderboardSnapshot([row('me', 25, 125), row('other', 25, 700)], 'me'); expect(result.enabled).toBe(true); expect(result.entries).toHaveLength(20); expect(result.entries.filter(entry => entry.isMock)).toHaveLength(18); expect(result.entries.map(entry => entry.leaguePoints)).toEqual([...result.entries.map(entry => entry.leaguePoints)].sort((a,b)=>b-a)); expect(result.currentUser).toEqual({ rank: 19, leaguePoints: 125 }) })
  test('personalized nearby context returns at most Top 20 and no population field', () => { const rows = Array.from({ length: 35 }, (_, i) => row(`u${i}`, 11 + i % 20, i)); const result = buildTierDLeaderboardSnapshot(rows, 'u10', { minimumEligibleMembers: 1, contextTarget: 30, maxDisplayed: 20 }); expect(result.enabled).toBe(true); expect(result.entries).toHaveLength(20); expect(result).not.toHaveProperty('population') })
  test('different nearby players receive distinct snapshots', () => { const rows = Array.from({ length: 31 }, (_, i) => row(`u${i}`, 11 + i % 20, i)); const a = buildTierDLeaderboardSnapshot(rows, 'u1', { minimumEligibleMembers: 1, contextTarget: 10, maxDisplayed: 20 }); const b = buildTierDLeaderboardSnapshot(rows, 'u29', { minimumEligibleMembers: 1, contextTarget: 10, maxDisplayed: 20 }); expect(a.entries.map(x => x.userId)).not.toEqual(b.entries.map(x => x.userId)) })
  test('ties use deterministic update then user-id order', () => { const result = buildTierDLeaderboardSnapshot([row('b', 30, 10), row('a', 30, 10)], 'a', { minimumEligibleMembers: 1, contextTarget: 30, maxDisplayed: 20 }); expect(result.entries.filter(x=>!x.isMock).map(x => x.userId)).toEqual(['a', 'b']) })
  test.each([[1, true], [2, true], [3, true], [4, false]])('final rank %i trophy eligibility is %s', (rank, eligible) => expect(trophyEligibleForFinalRank(rank)).toBe(eligible))
})
