import fs from 'fs'
import path from 'path'
import { MINI_TOURNAMENT_COHORT_SIZE, MINI_TOURNAMENT_DURATION_MS, MINI_TOURNAMENT_MIN_LEVEL, MINI_TOURNAMENT_REWARD_BANDS, MINI_TOURNAMENT_TRIGGER, MINI_TOURNAMENT_TRIGGER_RATE, advanceSyntheticEntries, createMiniTournamentWindow, miniTournamentStatus, rankMiniTournament, shouldTriggerPersonalTournament, syntheticEntries, tournamentRewardBand, tournamentScore, tournamentTokenReward, tournamentTrophy } from '../../src/game/tierDMiniTournament'

describe('Personal 24-hour Top 20 tournament',()=>{
 test('eligibility starts at Lv.100 and trigger is exactly 2/18',()=>{expect(MINI_TOURNAMENT_MIN_LEVEL).toBe(100);expect(MINI_TOURNAMENT_TRIGGER).toEqual({numerator:2,denominator:18});expect(MINI_TOURNAMENT_TRIGGER_RATE).toBe(2/18);expect(shouldTriggerPersonalTournament(2/18-Number.EPSILON)).toBe(true);expect(shouldTriggerPersonalTournament(2/18)).toBe(false)})
 test('expires at exactly 24 hours',()=>{const w=createMiniTournamentWindow(1000);expect(w.endAt-w.startAt).toBe(MINI_TOURNAMENT_DURATION_MS);expect(miniTournamentStatus(w.endAt,w.endAt-1)).toBe('OPEN');expect(miniTournamentStatus(w.endAt,w.endAt)).toBe('LOCKED')})
 test('score is authoritative current total minus immutable baseline',()=>{expect(tournamentScore(170,100)).toBe(70);expect(tournamentScore(90,100)).toBe(0)})
 test('fixed cohort target is in requested 30-40 range',()=>{expect(MINI_TOURNAMENT_COHORT_SIZE).toBeGreaterThanOrEqual(30);expect(MINI_TOURNAMENT_COHORT_SIZE).toBeLessThanOrEqual(40);expect(syntheticEntries('t',100,4)).toEqual(syntheticEntries('t',100,4))})
 test('mocks progress irregularly by only zero or 5-10 per opportunity and never use owner score',()=>{const start=1000;let rows=syntheticEntries('t',100,8);const next=advanceSyntheticEntries(rows,start,start+15*60_000,'t');next.forEach((row,i)=>expect([0,5,6,7,8,9,10]).toContain(row.points-rows[i].points));expect(advanceSyntheticEntries(next,start,start+15*60_000,'t')).toEqual(next)})
 test('ranking uses tournament delta and exposes owner rank outside Top 20',()=>{const ranked=rankMiniTournament(Array.from({length:25},(_,i)=>({userId:i===24?'owner':`u${i}`,level:100,points:25-i,updatedAt:i})));expect(ranked.slice(0,20)).toHaveLength(20);expect(ranked.find(row=>row.userId==='owner')?.rank).toBe(25)})
 test('ties and repeated ranking are deterministic',()=>{const rows=[{userId:'b',level:5,points:10,updatedAt:2},{userId:'a',level:5,points:10,updatedAt:1}];expect(rankMiniTournament(rows).map(x=>x.userId)).toEqual(['a','b']);expect(rankMiniTournament(rows)).toEqual(rankMiniTournament(rows))})
 test('all S-curve reward bands lock exact token values',()=>{expect(MINI_TOURNAMENT_REWARD_BANDS).toHaveLength(10);expect(tournamentRewardBand(99)).toBeUndefined();expect(tournamentRewardBand(100)).toEqual({rank1:1000,rank2:500,rank3:200,rank4To20:100});expect(tournamentRewardBand(1000)).toEqual({rank1:5000,rank2:3000,rank3:2000,rank4To20:1000});const band=tournamentRewardBand(500)!;expect([1,2,3,4,20,21].map(rank=>tournamentTokenReward(rank,band))).toEqual([2500,1500,1000,550,550,0])})
 test('Top 3 trophy and champion assignment is canonical',()=>{expect([1,2,3,4].map(tournamentTrophy)).toEqual(['Gold','Silver','Bronze',null])})
})

describe('personal tournament persistence schema',()=>{
 const oldSql=fs.readFileSync(path.resolve(__dirname,'../../../supabase/migrations/081_tier_d_personal_mini_tournaments.sql'),'utf8')
 const sql=fs.readFileSync(path.resolve(__dirname,'../../../supabase/migrations/085_personal_top20_tournaments.sql'),'utf8')
 const finalSql=fs.readFileSync(path.resolve(__dirname,'../../../supabase/migrations/086_personal_top20_final_rules.sql'),'utf8')
 const service=fs.readFileSync(path.resolve(__dirname,'../../src/game/tierDMiniTournamentService.ts'),'utf8')
 test('one active owned tournament and overlapping membership in other owners cohorts are supported',()=>{expect(oldSql).toContain('tier_d_one_open_personal_tournament');expect(oldSql).toContain("WHERE status='OPEN'");expect(sql).toContain('tier_d_personal_tournament_real_members');expect(sql).not.toContain('UNIQUE(user_id)')})
 test('cohort baselines, frozen scores, last seen rank and one roll per Level are durable',()=>{expect(sql).toContain('baseline_score');expect(sql).toContain('final_score');expect(sql).toContain('last_seen_rank');expect(sql).toContain('PRIMARY KEY(user_id,level)')})
 test('reward table remains idempotent per tournament owner',()=>{const rewardSql=fs.readFileSync(path.resolve(__dirname,'../../../supabase/migrations/079_tier_d_mini_tournament_rewards.sql'),'utf8');expect(rewardSql).toContain('PRIMARY KEY(tournament_id,user_id)')})
 test('frozen reward band, podium trophy and champion status are persisted',()=>{expect(finalSql).toContain('reward_band jsonb');expect(finalSql).toContain('token_reward');expect(finalSql).toContain('trophy_type');expect(finalSql).toContain('champion boolean')})
 test('finalization claims OPEN once and reward retries share a ledger idempotency key',()=>{expect(service).toContain(".eq('id',event.id).eq('status','OPEN').select('id')");expect(service).toContain('await settleOwnerReward(event,owner.rank)');expect(service).toContain('TIER_D_PERSONAL_TOP20:${event.id}:${event.owner_user_id}')})
 test('an owned active tournament suppresses eligibility checks and RNG',()=>{const activeCheck=service.indexOf('if(active)return');const eligibilityCheck=service.indexOf('if(level<MINI_TOURNAMENT_MIN_LEVEL)');const randomCall=service.indexOf('random()');expect(activeCheck).toBeGreaterThan(0);expect(activeCheck).toBeLessThan(eligibilityCheck);expect(eligibilityCheck).toBeLessThan(randomCall)})
 test('real cohort membership is inserted once and standings refresh lifetime totals instead of rerolling members',()=>{expect(service).toContain("from('tier_d_mini_tournament_entries').insert([...entries,...mocks])");expect(service).toContain("from('tier_d_ranking_score_totals').select('user_id,total_score')");expect(service).not.toContain('rubber')})
})
