// app/(home)/_layout.tsx
// Auth Guard สำหรับทุกหน้าใน group (home)
// ต้องมี session + display_name ถึงจะเข้าได้
import { Stack, Redirect } from 'expo-router'
import { useAuthStore } from '../../src/store/authStore'
import { View, ActivityIndicator } from 'react-native'

export default function HomeLayout() {
  const { isInitialized, session, profile } = useAuthStore()

  // ยังเช็ค session ไม่เสร็จ -- รอก่อน
  if (!isInitialized) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#0F2418' }}>
        <ActivityIndicator color="#FFD76A" />
      </View>
    )
  }

  // ไม่มี session -- เด้งไปหน้า login
  if (!session) return <Redirect href="/(auth)/login" />

  // มี session แต่ยังไม่มี display_name -- เด้งไปตั้งโปรไฟล์ก่อน
  const isAutoGeneratedName = profile?.display_name
    ? /^user_[a-f0-9]{8}$/.test(profile.display_name)
    : true
  if (!profile?.display_name || isAutoGeneratedName) return <Redirect href="/(auth)/setup-profile" />

  return <Stack screenOptions={{ headerShown: false }} />
}
