import React, { useCallback, useEffect, useState } from 'react'
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native'
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router'
import { useSafeAreaInsets } from 'react-native-safe-area-context'
import { useAuthStore } from '../../src/store/authStore'

const SERVER_URL = process.env.EXPO_PUBLIC_SERVER_URL || 'http://localhost:3001'
type Status = { cycleDay:number; multiplier:number; eligible:boolean; requiresRewardedAd:boolean; membership:string; dailyBaseToken:number; protectionsUsed:number }
type Claim = { cycleDay:number; items:{itemKey:string;quantity:number}[]; tokenAmount:number; socialItem?:'heart'|'rose'; idempotent:boolean }

export default function StreakScreen() {
 const insets=useSafeAreaInsets(), params=useLocalSearchParams<{dailyClaim?:string;googleTestEarned?:string}>(), token=useAuthStore(s=>s.session?.access_token)
 const [status,setStatus]=useState<Status>(),[claim,setClaim]=useState<Claim>(),[social,setSocial]=useState({heart:0,rose:0}),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const headers:Record<string,string>=token?{Authorization:`Bearer ${token}`}:{ }
 const load=useCallback(async()=>{if(!token)return;const [state,inventory]=await Promise.all([fetch(`${SERVER_URL}/daily-streak`,{headers}),fetch(`${SERVER_URL}/inventory/social-items`,{headers})]);if(state.ok)setStatus(await state.json());if(inventory.ok)setSocial((await inventory.json()).inventory)},[token])
 useFocusEffect(useCallback(()=>{void load()},[load]))
 const claimDirect=useCallback(async(devMock=false,googleTestEarned=false)=>{if(!token||busy)return;setBusy(true);setError('');try{const response=await fetch(`${SERVER_URL}/daily-streak/claim`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({devMock,googleTestEarned})});const body=await response.json();if(!response.ok)throw new Error(body.error??'Claim unavailable');setClaim(body);await load()}catch(e){setError(e instanceof Error?e.message:'Claim unavailable')}finally{setBusy(false)}},[token,busy,load])
 useEffect(()=>{if(params.dailyClaim==='1'){const googleTestEarned=params.googleTestEarned==='1';router.setParams({dailyClaim:undefined,googleTestEarned:undefined} as any);void claimDirect(!googleTestEarned,googleTestEarned)}},[params.dailyClaim,params.googleTestEarned,claimDirect])
 const press=()=>{if(!status?.eligible)return;if(status.requiresRewardedAd){router.push({pathname:'/(home)/watch-ad',params:{returnTo:'/(home)/streak?dailyClaim=1',mode:'daily_streak'}} as any);return}void claimDirect()}
 const nextDay=status?.cycleDay||1, quantity=status?.multiplier||1
 return <View style={[s.page,{paddingTop:insets.top+16}]}><Text style={s.title}>DAILY STREAK</Text><Text style={s.sub}>Complete one game each Bangkok day to unlock today’s claim.</Text><View style={s.card}><Text style={s.day}>DAY {nextDay} · ×{quantity}</Text><Text style={s.label}>GAMEPLAY REWARD</Text><Text style={s.reward}>{quantity} RANDOM ITEM{quantity>1?'S':''}</Text><Text style={s.reward}>🪙 {((status?.dailyBaseToken||0)*quantity).toLocaleString()} TOKEN</Text>{status?.membership==='VIP_PRO_PLUS'?<><Text style={s.label}>PRO PLUS SOCIAL BONUS</Text><Text style={s.social}>❤️ HEART ×1 OR 🌹 ROSE ×1</Text><Text style={s.note}>A social gift. It has no gameplay effect.</Text></>:null}<Text style={s.protection}>MISSED-DAY PROTECTION USED: {status?.protectionsUsed??0}</Text></View>{claim?<View style={s.result}><Text style={s.resultTitle}>DAILY REWARD CLAIMED</Text><Text style={s.reward}>{claim.items.map(x=>`${x.itemKey.replaceAll('_',' ').toUpperCase()} ×${x.quantity}`).join(' · ')}</Text><Text style={s.reward}>🪙 {claim.tokenAmount.toLocaleString()} TOKEN</Text>{claim.socialItem?<><Text style={s.label}>PRO PLUS SOCIAL BONUS</Text><Text style={s.social}>{claim.socialItem==='heart'?'❤️ HEART ×1':'🌹 ROSE ×1'}</Text></>:null}</View>:null}{error?<Text style={s.error}>{error}</Text>:null}<TouchableOpacity disabled={!status?.eligible||busy} onPress={press} style={[s.button,(!status?.eligible||busy)&&s.disabled]}><Text style={s.buttonText}>{busy?'CLAIMING…':!status?.eligible?'PLAY A GAME TO UNLOCK':status.requiresRewardedAd?'WATCH AD TO CLAIM':'CLAIM DAILY REWARD'}</Text></TouchableOpacity><Text style={s.inventory}>SOCIAL INVENTORY · ❤️ {social.heart}   🌹 {social.rose}</Text></View>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0b1611',alignItems:'center',paddingHorizontal:20},title:{color:'#FFD76A',fontWeight:'900',fontSize:28},sub:{color:'#c8c4b0',textAlign:'center',marginTop:10},card:{width:'100%',marginTop:24,borderWidth:1,borderColor:'#48634d',backgroundColor:'#153020',borderRadius:16,padding:20,gap:8},day:{color:'#fff2b0',fontWeight:'900',fontSize:20},label:{color:'#FFD76A',fontWeight:'800',fontSize:12,marginTop:9},reward:{color:'#f7f4e9',fontWeight:'700'},social:{color:'#ffb5bf',fontWeight:'900',fontSize:16},note:{color:'#b9c6b8',fontSize:12},protection:{color:'#94ad98',fontSize:12,marginTop:10},result:{width:'100%',marginTop:16,padding:16,borderRadius:12,backgroundColor:'#253923',gap:5},resultTitle:{color:'#8DFFB5',fontWeight:'900'},button:{width:'100%',marginTop:20,padding:16,borderRadius:12,backgroundColor:'#9b6719',alignItems:'center'},disabled:{opacity:.45},buttonText:{color:'#fff8dc',fontWeight:'900'},error:{color:'#ff9d9d',marginTop:12,textAlign:'center'},inventory:{color:'#c8c4b0',marginTop:18,fontWeight:'700'}})
