import React, { useEffect, useState } from 'react'
import { ActivityIndicator, Image, Pressable, StyleSheet, Text, View } from 'react-native'
import { router, useLocalSearchParams } from 'expo-router'
import { useAuthStore } from '../../../../src/store/authStore'
import { ThemedBackground } from '../../../../src/components/ui/ThemedBackground'

const SERVER_URL=process.env.EXPO_PUBLIC_SERVER_URL||'http://localhost:3001'
const CASE=require('../../../../assets/images/trophy_showcase.png')
const MEDAL=require('../../../../assets/images/triplepoker_coin.png')
const trophies:Record<string,number>={bronze:require('../../../../assets/league/Bronze League Trophy.png'),silver:require('../../../../assets/league/Silver League Trophy.png'),gold:require('../../../../assets/league/Gold League Trophy.png'),platinum:require('../../../../assets/league/Platinum League Trophy.png'),diamond:require('../../../../assets/league/Diamond League Trophy.png'),elite:require('../../../../assets/league/Elite League Trophy.png'),master:require('../../../../assets/league/Master League Trophy.png'),grandmaster:require('../../../../assets/league/Grandmaster League Trophy.png'),legend:require('../../../../assets/league/Legend League Trophy.png'),mythic:require('../../../../assets/league/Champion League Trophy.png')}
type Award={league_id:string;award_type:'medal'|'trophy';final_rank:number;league_name:string;awarded_at:string}
const slots=[[.16,.77],[.5,.77],[.84,.77],[.16,.59],[.5,.59],[.84,.59],[.16,.41],[.5,.41],[.84,.41],[.16,.23]] as const
export default function PlayerShowcase(){const {userId}=useLocalSearchParams<{userId:string}>();const token=useAuthStore(s=>s.session?.access_token);const vip=useAuthStore(s=>(s.profile?.vip_status??'none')!=='none');const [awards,setAwards]=useState<Award[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{if(!userId||!token)return;fetch(`${SERVER_URL}/tier-d/showcase/${userId}`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.ok?r.json():Promise.reject()).then(x=>setAwards(x.awards??[])).catch(()=>setAwards([])).finally(()=>setLoading(false))},[token,userId]);const grouped=new Map<string,Award[]>();awards.forEach(a=>grouped.set(a.league_id,[...(grouped.get(a.league_id)??[]),a]));return <ThemedBackground isVip={vip}><View style={s.root}><Pressable style={s.back} onPress={()=>router.back()}><Text style={s.backText}>‹ BACK</Text></Pressable><Text style={s.title}>TROPHY SHOWCASE</Text><Text style={s.sub}>LEAGUE AWARDS & COLLECTED HONORS</Text>{loading?<ActivityIndicator color="#FFD76A" style={s.loading}/>:<View style={s.cases}>{(['left','right'] as const).map(side=><View key={side} style={s.case}><Image source={CASE} resizeMode="stretch" style={[s.caseImage,side==='right'&&s.mirror]}/>{[...grouped.entries()].map(([league,items],index)=>{const slot=slots[index];return <View key={league} style={[s.prize,{left:`${slot[0]*100}%`,top:`${slot[1]*100}%`}]}>{items.some(a=>a.award_type==='trophy')&&trophies[league]?<Image source={trophies[league]} resizeMode="contain" style={s.trophy}/>:null}{items.some(a=>a.award_type==='medal')?<Image source={MEDAL} resizeMode="contain" style={s.medal}/>:null}</View>})}</View>)}</View>}<Text style={s.count}>{awards.length?`${awards.length} AWARD${awards.length===1?'':'S'} COLLECTED`:'NO AWARDS YET — KEEP CLIMBING'}</Text></View></ThemedBackground>}
const s=StyleSheet.create({root:{flex:1,alignItems:'center',paddingTop:22},back:{position:'absolute',left:14,top:16,zIndex:2,borderWidth:1,borderColor:'#FFD76A',borderRadius:8,paddingHorizontal:10,paddingVertical:7},backText:{color:'#FFD76A',fontSize:10,fontWeight:'900'},title:{color:'#FFD76A',fontSize:24,fontWeight:'900',letterSpacing:1.5,marginTop:20},sub:{color:'#a9d5bf',fontSize:9,fontWeight:'800',letterSpacing:.8,marginTop:4},loading:{marginTop:100},cases:{flexDirection:'row',gap:22,width:'100%',justifyContent:'center',marginTop:70},case:{position:'relative',width:132,height:268},caseImage:{...StyleSheet.absoluteFill},mirror:{transform:[{scaleX:-1}]},prize:{position:'absolute',width:34,height:34,marginLeft:-17,marginTop:-17,alignItems:'center',justifyContent:'center'},trophy:{width:29,height:29},medal:{position:'absolute',width:13,height:13,right:-2,bottom:-2},count:{color:'#fff1bb',fontSize:11,fontWeight:'900',letterSpacing:1,marginTop:22}})
