// Generated from flag-icons 7.5.0 ISO country/territory metadata.
export const COUNTRIES = [
  {code:"AF",name:"Afghanistan",image:require('../../assets/countries/af.png')},
  {code:"AX",name:"Aland Islands",image:require('../../assets/countries/ax.png')},
  {code:"AL",name:"Albania",image:require('../../assets/countries/al.png')},
  {code:"DZ",name:"Algeria",image:require('../../assets/countries/dz.png')},
  {code:"AS",name:"American Samoa",image:require('../../assets/countries/as.png')},
  {code:"AD",name:"Andorra",image:require('../../assets/countries/ad.png')},
  {code:"AO",name:"Angola",image:require('../../assets/countries/ao.png')},
  {code:"AI",name:"Anguilla",image:require('../../assets/countries/ai.png')},
  {code:"AQ",name:"Antarctica",image:require('../../assets/countries/aq.png')},
  {code:"AG",name:"Antigua and Barbuda",image:require('../../assets/countries/ag.png')},
  {code:"AR",name:"Argentina",image:require('../../assets/countries/ar.png')},
  {code:"AM",name:"Armenia",image:require('../../assets/countries/am.png')},
  {code:"AW",name:"Aruba",image:require('../../assets/countries/aw.png')},
  {code:"AU",name:"Australia",image:require('../../assets/countries/au.png')},
  {code:"AT",name:"Austria",image:require('../../assets/countries/at.png')},
  {code:"AZ",name:"Azerbaijan",image:require('../../assets/countries/az.png')},
  {code:"BS",name:"Bahamas",image:require('../../assets/countries/bs.png')},
  {code:"BH",name:"Bahrain",image:require('../../assets/countries/bh.png')},
  {code:"BD",name:"Bangladesh",image:require('../../assets/countries/bd.png')},
  {code:"BB",name:"Barbados",image:require('../../assets/countries/bb.png')},
  {code:"BY",name:"Belarus",image:require('../../assets/countries/by.png')},
  {code:"BE",name:"Belgium",image:require('../../assets/countries/be.png')},
  {code:"BZ",name:"Belize",image:require('../../assets/countries/bz.png')},
  {code:"BJ",name:"Benin",image:require('../../assets/countries/bj.png')},
  {code:"BM",name:"Bermuda",image:require('../../assets/countries/bm.png')},
  {code:"BT",name:"Bhutan",image:require('../../assets/countries/bt.png')},
  {code:"BO",name:"Bolivia",image:require('../../assets/countries/bo.png')},
  {code:"BQ",name:"Bonaire, Sint Eustatius and Saba",image:require('../../assets/countries/bq.png')},
  {code:"BA",name:"Bosnia and Herzegovina",image:require('../../assets/countries/ba.png')},
  {code:"BW",name:"Botswana",image:require('../../assets/countries/bw.png')},
  {code:"BV",name:"Bouvet Island",image:require('../../assets/countries/bv.png')},
  {code:"BR",name:"Brazil",image:require('../../assets/countries/br.png')},
  {code:"IO",name:"British Indian Ocean Territory",image:require('../../assets/countries/io.png')},
  {code:"BN",name:"Brunei Darussalam",image:require('../../assets/countries/bn.png')},
  {code:"BG",name:"Bulgaria",image:require('../../assets/countries/bg.png')},
  {code:"BF",name:"Burkina Faso",image:require('../../assets/countries/bf.png')},
  {code:"BI",name:"Burundi",image:require('../../assets/countries/bi.png')},
  {code:"CV",name:"Cabo Verde",image:require('../../assets/countries/cv.png')},
  {code:"KH",name:"Cambodia",image:require('../../assets/countries/kh.png')},
  {code:"CM",name:"Cameroon",image:require('../../assets/countries/cm.png')},
  {code:"CA",name:"Canada",image:require('../../assets/countries/ca.png')},
  {code:"KY",name:"Cayman Islands",image:require('../../assets/countries/ky.png')},
  {code:"CF",name:"Central African Republic",image:require('../../assets/countries/cf.png')},
  {code:"TD",name:"Chad",image:require('../../assets/countries/td.png')},
  {code:"CL",name:"Chile",image:require('../../assets/countries/cl.png')},
  {code:"CN",name:"China",image:require('../../assets/countries/cn.png')},
  {code:"CX",name:"Christmas Island",image:require('../../assets/countries/cx.png')},
  {code:"CC",name:"Cocos (Keeling) Islands",image:require('../../assets/countries/cc.png')},
  {code:"CO",name:"Colombia",image:require('../../assets/countries/co.png')},
  {code:"KM",name:"Comoros",image:require('../../assets/countries/km.png')},
  {code:"CK",name:"Cook Islands",image:require('../../assets/countries/ck.png')},
  {code:"CR",name:"Costa Rica",image:require('../../assets/countries/cr.png')},
  {code:"CI",name:"Côte d'Ivoire",image:require('../../assets/countries/ci.png')},
  {code:"HR",name:"Croatia",image:require('../../assets/countries/hr.png')},
  {code:"CU",name:"Cuba",image:require('../../assets/countries/cu.png')},
  {code:"CW",name:"Curaçao",image:require('../../assets/countries/cw.png')},
  {code:"CY",name:"Cyprus",image:require('../../assets/countries/cy.png')},
  {code:"CZ",name:"Czech Republic",image:require('../../assets/countries/cz.png')},
  {code:"CD",name:"Democratic Republic of the Congo",image:require('../../assets/countries/cd.png')},
  {code:"DK",name:"Denmark",image:require('../../assets/countries/dk.png')},
  {code:"DJ",name:"Djibouti",image:require('../../assets/countries/dj.png')},
  {code:"DM",name:"Dominica",image:require('../../assets/countries/dm.png')},
  {code:"DO",name:"Dominican Republic",image:require('../../assets/countries/do.png')},
  {code:"EC",name:"Ecuador",image:require('../../assets/countries/ec.png')},
  {code:"EG",name:"Egypt",image:require('../../assets/countries/eg.png')},
  {code:"SV",name:"El Salvador",image:require('../../assets/countries/sv.png')},
  {code:"GQ",name:"Equatorial Guinea",image:require('../../assets/countries/gq.png')},
  {code:"ER",name:"Eritrea",image:require('../../assets/countries/er.png')},
  {code:"EE",name:"Estonia",image:require('../../assets/countries/ee.png')},
  {code:"SZ",name:"Eswatini",image:require('../../assets/countries/sz.png')},
  {code:"ET",name:"Ethiopia",image:require('../../assets/countries/et.png')},
  {code:"FK",name:"Falkland Islands",image:require('../../assets/countries/fk.png')},
  {code:"FO",name:"Faroe Islands",image:require('../../assets/countries/fo.png')},
  {code:"FM",name:"Federated States of Micronesia",image:require('../../assets/countries/fm.png')},
  {code:"FJ",name:"Fiji",image:require('../../assets/countries/fj.png')},
  {code:"FI",name:"Finland",image:require('../../assets/countries/fi.png')},
  {code:"FR",name:"France",image:require('../../assets/countries/fr.png')},
  {code:"GF",name:"French Guiana",image:require('../../assets/countries/gf.png')},
  {code:"PF",name:"French Polynesia",image:require('../../assets/countries/pf.png')},
  {code:"TF",name:"French Southern Territories",image:require('../../assets/countries/tf.png')},
  {code:"GA",name:"Gabon",image:require('../../assets/countries/ga.png')},
  {code:"GM",name:"Gambia",image:require('../../assets/countries/gm.png')},
  {code:"GE",name:"Georgia",image:require('../../assets/countries/ge.png')},
  {code:"DE",name:"Germany",image:require('../../assets/countries/de.png')},
  {code:"GH",name:"Ghana",image:require('../../assets/countries/gh.png')},
  {code:"GI",name:"Gibraltar",image:require('../../assets/countries/gi.png')},
  {code:"GR",name:"Greece",image:require('../../assets/countries/gr.png')},
  {code:"GL",name:"Greenland",image:require('../../assets/countries/gl.png')},
  {code:"GD",name:"Grenada",image:require('../../assets/countries/gd.png')},
  {code:"GP",name:"Guadeloupe",image:require('../../assets/countries/gp.png')},
  {code:"GU",name:"Guam",image:require('../../assets/countries/gu.png')},
  {code:"GT",name:"Guatemala",image:require('../../assets/countries/gt.png')},
  {code:"GG",name:"Guernsey",image:require('../../assets/countries/gg.png')},
  {code:"GN",name:"Guinea",image:require('../../assets/countries/gn.png')},
  {code:"GW",name:"Guinea-Bissau",image:require('../../assets/countries/gw.png')},
  {code:"GY",name:"Guyana",image:require('../../assets/countries/gy.png')},
  {code:"HT",name:"Haiti",image:require('../../assets/countries/ht.png')},
  {code:"HM",name:"Heard Island and McDonald Islands",image:require('../../assets/countries/hm.png')},
  {code:"VA",name:"Holy See",image:require('../../assets/countries/va.png')},
  {code:"HN",name:"Honduras",image:require('../../assets/countries/hn.png')},
  {code:"HK",name:"Hong Kong",image:require('../../assets/countries/hk.png')},
  {code:"HU",name:"Hungary",image:require('../../assets/countries/hu.png')},
  {code:"IS",name:"Iceland",image:require('../../assets/countries/is.png')},
  {code:"IN",name:"India",image:require('../../assets/countries/in.png')},
  {code:"ID",name:"Indonesia",image:require('../../assets/countries/id.png')},
  {code:"IR",name:"Iran",image:require('../../assets/countries/ir.png')},
  {code:"IQ",name:"Iraq",image:require('../../assets/countries/iq.png')},
  {code:"IE",name:"Ireland",image:require('../../assets/countries/ie.png')},
  {code:"IM",name:"Isle of Man",image:require('../../assets/countries/im.png')},
  {code:"IL",name:"Israel",image:require('../../assets/countries/il.png')},
  {code:"IT",name:"Italy",image:require('../../assets/countries/it.png')},
  {code:"JM",name:"Jamaica",image:require('../../assets/countries/jm.png')},
  {code:"JP",name:"Japan",image:require('../../assets/countries/jp.png')},
  {code:"JE",name:"Jersey",image:require('../../assets/countries/je.png')},
  {code:"JO",name:"Jordan",image:require('../../assets/countries/jo.png')},
  {code:"KZ",name:"Kazakhstan",image:require('../../assets/countries/kz.png')},
  {code:"KE",name:"Kenya",image:require('../../assets/countries/ke.png')},
  {code:"KI",name:"Kiribati",image:require('../../assets/countries/ki.png')},
  {code:"KW",name:"Kuwait",image:require('../../assets/countries/kw.png')},
  {code:"KG",name:"Kyrgyzstan",image:require('../../assets/countries/kg.png')},
  {code:"LA",name:"Laos",image:require('../../assets/countries/la.png')},
  {code:"LV",name:"Latvia",image:require('../../assets/countries/lv.png')},
  {code:"LB",name:"Lebanon",image:require('../../assets/countries/lb.png')},
  {code:"LS",name:"Lesotho",image:require('../../assets/countries/ls.png')},
  {code:"LR",name:"Liberia",image:require('../../assets/countries/lr.png')},
  {code:"LY",name:"Libya",image:require('../../assets/countries/ly.png')},
  {code:"LI",name:"Liechtenstein",image:require('../../assets/countries/li.png')},
  {code:"LT",name:"Lithuania",image:require('../../assets/countries/lt.png')},
  {code:"LU",name:"Luxembourg",image:require('../../assets/countries/lu.png')},
  {code:"MO",name:"Macau",image:require('../../assets/countries/mo.png')},
  {code:"MG",name:"Madagascar",image:require('../../assets/countries/mg.png')},
  {code:"MW",name:"Malawi",image:require('../../assets/countries/mw.png')},
  {code:"MY",name:"Malaysia",image:require('../../assets/countries/my.png')},
  {code:"MV",name:"Maldives",image:require('../../assets/countries/mv.png')},
  {code:"ML",name:"Mali",image:require('../../assets/countries/ml.png')},
  {code:"MT",name:"Malta",image:require('../../assets/countries/mt.png')},
  {code:"MH",name:"Marshall Islands",image:require('../../assets/countries/mh.png')},
  {code:"MQ",name:"Martinique",image:require('../../assets/countries/mq.png')},
  {code:"MR",name:"Mauritania",image:require('../../assets/countries/mr.png')},
  {code:"MU",name:"Mauritius",image:require('../../assets/countries/mu.png')},
  {code:"YT",name:"Mayotte",image:require('../../assets/countries/yt.png')},
  {code:"MX",name:"Mexico",image:require('../../assets/countries/mx.png')},
  {code:"MD",name:"Moldova",image:require('../../assets/countries/md.png')},
  {code:"MC",name:"Monaco",image:require('../../assets/countries/mc.png')},
  {code:"MN",name:"Mongolia",image:require('../../assets/countries/mn.png')},
  {code:"ME",name:"Montenegro",image:require('../../assets/countries/me.png')},
  {code:"MS",name:"Montserrat",image:require('../../assets/countries/ms.png')},
  {code:"MA",name:"Morocco",image:require('../../assets/countries/ma.png')},
  {code:"MZ",name:"Mozambique",image:require('../../assets/countries/mz.png')},
  {code:"MM",name:"Myanmar",image:require('../../assets/countries/mm.png')},
  {code:"NA",name:"Namibia",image:require('../../assets/countries/na.png')},
  {code:"NR",name:"Nauru",image:require('../../assets/countries/nr.png')},
  {code:"NP",name:"Nepal",image:require('../../assets/countries/np.png')},
  {code:"NL",name:"Netherlands",image:require('../../assets/countries/nl.png')},
  {code:"NC",name:"New Caledonia",image:require('../../assets/countries/nc.png')},
  {code:"NZ",name:"New Zealand",image:require('../../assets/countries/nz.png')},
  {code:"NI",name:"Nicaragua",image:require('../../assets/countries/ni.png')},
  {code:"NE",name:"Niger",image:require('../../assets/countries/ne.png')},
  {code:"NG",name:"Nigeria",image:require('../../assets/countries/ng.png')},
  {code:"NU",name:"Niue",image:require('../../assets/countries/nu.png')},
  {code:"NF",name:"Norfolk Island",image:require('../../assets/countries/nf.png')},
  {code:"KP",name:"North Korea",image:require('../../assets/countries/kp.png')},
  {code:"MK",name:"North Macedonia",image:require('../../assets/countries/mk.png')},
  {code:"MP",name:"Northern Mariana Islands",image:require('../../assets/countries/mp.png')},
  {code:"NO",name:"Norway",image:require('../../assets/countries/no.png')},
  {code:"OM",name:"Oman",image:require('../../assets/countries/om.png')},
  {code:"PK",name:"Pakistan",image:require('../../assets/countries/pk.png')},
  {code:"PW",name:"Palau",image:require('../../assets/countries/pw.png')},
  {code:"PA",name:"Panama",image:require('../../assets/countries/pa.png')},
  {code:"PG",name:"Papua New Guinea",image:require('../../assets/countries/pg.png')},
  {code:"PY",name:"Paraguay",image:require('../../assets/countries/py.png')},
  {code:"PE",name:"Peru",image:require('../../assets/countries/pe.png')},
  {code:"PH",name:"Philippines",image:require('../../assets/countries/ph.png')},
  {code:"PN",name:"Pitcairn",image:require('../../assets/countries/pn.png')},
  {code:"PL",name:"Poland",image:require('../../assets/countries/pl.png')},
  {code:"PT",name:"Portugal",image:require('../../assets/countries/pt.png')},
  {code:"PR",name:"Puerto Rico",image:require('../../assets/countries/pr.png')},
  {code:"QA",name:"Qatar",image:require('../../assets/countries/qa.png')},
  {code:"CG",name:"Republic of the Congo",image:require('../../assets/countries/cg.png')},
  {code:"RE",name:"Réunion",image:require('../../assets/countries/re.png')},
  {code:"RO",name:"Romania",image:require('../../assets/countries/ro.png')},
  {code:"RU",name:"Russia",image:require('../../assets/countries/ru.png')},
  {code:"RW",name:"Rwanda",image:require('../../assets/countries/rw.png')},
  {code:"BL",name:"Saint Barthélemy",image:require('../../assets/countries/bl.png')},
  {code:"SH",name:"Saint Helena, Ascension and Tristan da Cunha",image:require('../../assets/countries/sh.png')},
  {code:"KN",name:"Saint Kitts and Nevis",image:require('../../assets/countries/kn.png')},
  {code:"LC",name:"Saint Lucia",image:require('../../assets/countries/lc.png')},
  {code:"MF",name:"Saint Martin",image:require('../../assets/countries/mf.png')},
  {code:"PM",name:"Saint Pierre and Miquelon",image:require('../../assets/countries/pm.png')},
  {code:"VC",name:"Saint Vincent and the Grenadines",image:require('../../assets/countries/vc.png')},
  {code:"WS",name:"Samoa",image:require('../../assets/countries/ws.png')},
  {code:"SM",name:"San Marino",image:require('../../assets/countries/sm.png')},
  {code:"ST",name:"Sao Tome and Principe",image:require('../../assets/countries/st.png')},
  {code:"SA",name:"Saudi Arabia",image:require('../../assets/countries/sa.png')},
  {code:"SN",name:"Senegal",image:require('../../assets/countries/sn.png')},
  {code:"RS",name:"Serbia",image:require('../../assets/countries/rs.png')},
  {code:"SC",name:"Seychelles",image:require('../../assets/countries/sc.png')},
  {code:"SL",name:"Sierra Leone",image:require('../../assets/countries/sl.png')},
  {code:"SG",name:"Singapore",image:require('../../assets/countries/sg.png')},
  {code:"SX",name:"Sint Maarten",image:require('../../assets/countries/sx.png')},
  {code:"SK",name:"Slovakia",image:require('../../assets/countries/sk.png')},
  {code:"SI",name:"Slovenia",image:require('../../assets/countries/si.png')},
  {code:"SB",name:"Solomon Islands",image:require('../../assets/countries/sb.png')},
  {code:"SO",name:"Somalia",image:require('../../assets/countries/so.png')},
  {code:"ZA",name:"South Africa",image:require('../../assets/countries/za.png')},
  {code:"GS",name:"South Georgia and the South Sandwich Islands",image:require('../../assets/countries/gs.png')},
  {code:"KR",name:"South Korea",image:require('../../assets/countries/kr.png')},
  {code:"SS",name:"South Sudan",image:require('../../assets/countries/ss.png')},
  {code:"ES",name:"Spain",image:require('../../assets/countries/es.png')},
  {code:"LK",name:"Sri Lanka",image:require('../../assets/countries/lk.png')},
  {code:"PS",name:"State of Palestine",image:require('../../assets/countries/ps.png')},
  {code:"SD",name:"Sudan",image:require('../../assets/countries/sd.png')},
  {code:"SR",name:"Suriname",image:require('../../assets/countries/sr.png')},
  {code:"SJ",name:"Svalbard and Jan Mayen",image:require('../../assets/countries/sj.png')},
  {code:"SE",name:"Sweden",image:require('../../assets/countries/se.png')},
  {code:"CH",name:"Switzerland",image:require('../../assets/countries/ch.png')},
  {code:"SY",name:"Syria",image:require('../../assets/countries/sy.png')},
  {code:"TW",name:"Taiwan",image:require('../../assets/countries/tw.png')},
  {code:"TJ",name:"Tajikistan",image:require('../../assets/countries/tj.png')},
  {code:"TZ",name:"Tanzania",image:require('../../assets/countries/tz.png')},
  {code:"TH",name:"Thailand",image:require('../../assets/countries/th.png')},
  {code:"TL",name:"Timor-Leste",image:require('../../assets/countries/tl.png')},
  {code:"TG",name:"Togo",image:require('../../assets/countries/tg.png')},
  {code:"TK",name:"Tokelau",image:require('../../assets/countries/tk.png')},
  {code:"TO",name:"Tonga",image:require('../../assets/countries/to.png')},
  {code:"TT",name:"Trinidad and Tobago",image:require('../../assets/countries/tt.png')},
  {code:"TN",name:"Tunisia",image:require('../../assets/countries/tn.png')},
  {code:"TR",name:"Türkiye",image:require('../../assets/countries/tr.png')},
  {code:"TM",name:"Turkmenistan",image:require('../../assets/countries/tm.png')},
  {code:"TC",name:"Turks and Caicos Islands",image:require('../../assets/countries/tc.png')},
  {code:"TV",name:"Tuvalu",image:require('../../assets/countries/tv.png')},
  {code:"UG",name:"Uganda",image:require('../../assets/countries/ug.png')},
  {code:"UA",name:"Ukraine",image:require('../../assets/countries/ua.png')},
  {code:"AE",name:"United Arab Emirates",image:require('../../assets/countries/ae.png')},
  {code:"GB",name:"United Kingdom",image:require('../../assets/countries/gb.png')},
  {code:"UM",name:"United States Minor Outlying Islands",image:require('../../assets/countries/um.png')},
  {code:"US",name:"United States of America",image:require('../../assets/countries/us.png')},
  {code:"UY",name:"Uruguay",image:require('../../assets/countries/uy.png')},
  {code:"UZ",name:"Uzbekistan",image:require('../../assets/countries/uz.png')},
  {code:"VU",name:"Vanuatu",image:require('../../assets/countries/vu.png')},
  {code:"VE",name:"Venezuela",image:require('../../assets/countries/ve.png')},
  {code:"VN",name:"Vietnam",image:require('../../assets/countries/vn.png')},
  {code:"VG",name:"Virgin Islands (British)",image:require('../../assets/countries/vg.png')},
  {code:"VI",name:"Virgin Islands (U.S.)",image:require('../../assets/countries/vi.png')},
  {code:"WF",name:"Wallis and Futuna",image:require('../../assets/countries/wf.png')},
  {code:"EH",name:"Western Sahara",image:require('../../assets/countries/eh.png')},
  {code:"YE",name:"Yemen",image:require('../../assets/countries/ye.png')},
  {code:"ZM",name:"Zambia",image:require('../../assets/countries/zm.png')},
  {code:"ZW",name:"Zimbabwe",image:require('../../assets/countries/zw.png')},
];
