// คำอธิบายกติกาและแบบทดสอบ ใช้ลำดับภาษาร่วมกับ catalog.ts
export const RULE_MESSAGES = `
Tap two private cards to swap them. Each pile combines your cards with its own two shared cards. Pile 3 uses the best three of your five.|แตะไพ่ของคุณสองใบเพื่อสลับ แต่ละกองรวมไพ่คุณกับไพ่กลางของกองนั้นสองใบ กอง 3 เลือกสามใบที่ดีที่สุดจากห้าใบของคุณ|点两张手牌交换。每组手牌配上该组两张公共牌，第3组从你的五张中选最好的三张。|手札2枚をタップして交換。各組は手札と専用の共通カード2枚を組み合わせます。組3は手札5枚から最良の3枚を選びます。|내 카드 두 장을 눌러 바꿔요. 각 더미는 내 카드와 해당 공용 카드 2장을 합쳐요. 더미 3은 내 5장 중 가장 좋은 3장을 써요.|Chạm hai lá riêng để đổi. Mỗi bộ kết hợp bài riêng với hai lá chung của bộ đó. Bộ 3 chọn ba lá tốt nhất từ năm lá.|Ketuk dua kartu sendiri untuk menukar. Setiap susunan memakai dua kartu bersama khususnya. Susunan 3 memilih tiga terbaik dari lima kartu Anda.|Toca dos cartas tuyas para cambiarlas. Cada grupo usa sus dos cartas comunes. El grupo 3 elige las tres mejores de tus cinco cartas.|Toque em duas cartas suas para trocar. Cada grupo usa suas duas cartas comuns. O grupo 3 escolhe as três melhores das suas cinco cartas.|Touchez deux de vos cartes pour échanger. Chaque groupe utilise ses deux cartes communes. Le groupe 3 choisit les trois meilleures de vos cinq cartes.
Keep Pile 1 <= Pile 2 <= Pile 3. Equal hands are legal. Win a pile: 1 point. Tie: 0.5 each. The seal adds 1 only on an outright win and is spent even on a loss or tie.|ให้ความแข็งกอง 1 ≤ กอง 2 ≤ กอง 3 เท่ากันได้ ชนะกองได้ 1 แต้ม เสมอได้คนละ 0.5 ตราเพิ่ม 1 เฉพาะเมื่อชนะ และใช้หมดแม้แพ้หรือเสมอ|保持第1组≤第2组≤第3组，允许同强度。获胜1分，平局各0.5分。印记仅在独胜时加1，输或平也会消耗。|強さは組1≤組2≤組3。同じ強さも有効。勝利1点、引き分け各0.5点。印は単独勝利のみ追加1点で、負けや引き分けでも消費します。|더미 1≤2≤3으로 놓고 같아도 돼요. 승리 1점, 무승부 각 0.5점. 인장은 단독 승리 때만 1점 추가하며 패배나 무승부에도 소모돼요.|Giữ bộ 1≤2≤3, bằng nhau vẫn hợp lệ. Thắng 1 điểm, hòa mỗi bên 0.5. Dấu ấn chỉ cộng 1 khi thắng riêng và vẫn mất khi thua hoặc hòa.|Kekuatan susunan 1≤2≤3, sama kuat boleh. Menang 1 poin, seri masing-masing 0.5. Segel menambah 1 hanya saat menang mutlak, dan habis meski kalah atau seri.|Mantén grupo 1≤2≤3; se permite igualdad. Ganar da 1 punto, empatar 0.5 cada uno. El sello añade 1 solo al ganar y se gasta también al perder o empatar.|Mantenha grupo 1≤2≤3; igualdade é válida. Vencer dá 1 ponto, empate 0.5 para cada. O selo adiciona 1 só ao vencer e é gasto também ao perder ou empatar.|Respectez groupe 1≤2≤3 ; l’égalité est permise. Victoire : 1 point ; égalité : 0.5 chacun. Le sceau ajoute 1 seulement en cas de victoire et se consomme même en défaite ou égalité.
Poker ranks, low to high: high card, pair, two pair, three of a kind, straight, flush, full house, four of a kind, straight flush. A royal flush is the highest straight flush.|อันดับจากต่ำไปสูง: ไพ่สูง หนึ่งคู่ สองคู่ ตอง เรียง สี ฟูลเฮาส์ โฟร์การ์ด เรียงสี โดยรอยัลฟลัชคือเรียงสีที่สูงที่สุด|牌型从低到高：高牌、一对、两对、三条、顺子、同花、葫芦、四条、同花顺。皇家同花顺是最高同花顺。|弱い順：ハイカード、ワンペア、ツーペア、スリーカード、ストレート、フラッシュ、フルハウス、フォーカード、ストレートフラッシュ。ロイヤルフラッシュが最高です。|낮은 순서: 하이 카드, 원 페어, 투 페어, 트리플, 스트레이트, 플러시, 풀 하우스, 포카드, 스트레이트 플러시. 로열 플러시가 가장 높아요.|Từ thấp đến cao: mậu thầu, một đôi, hai đôi, bộ ba, sảnh, thùng, cù lũ, tứ quý, thùng phá sảnh. Sảnh rồng đồng chất là cao nhất.|Urutan rendah ke tinggi: kartu tinggi, satu pasangan, dua pasangan, tiga sejenis, lurus, flush, full house, empat sejenis, straight flush. Royal flush adalah straight flush tertinggi.|De menor a mayor: carta alta, pareja, doble pareja, trío, escalera, color, full, póquer, escalera de color. La escalera real es la más alta.|Do menor ao maior: carta alta, um par, dois pares, trinca, sequência, flush, full house, quadra, sequência de mesmo naipe. Royal flush é a maior sequência de mesmo naipe.|Du plus faible au plus fort : carte haute, paire, deux paires, brelan, quinte, couleur, full, carré, quinte flush. La quinte flush royale est la plus forte.
Both players have one seal per match. Robin locks its plan without seeing your hand. Tied final scores share the match.|ผู้เล่นทั้งสองมีตราคนละหนึ่งครั้งต่อแมตช์ Robin ล็อกแผนโดยไม่เห็นไพ่คุณ หากแต้มจบเท่ากันถือว่าเสมอ|双方每局各有一个印记。Robin不看你的手牌就锁定策略。最终同分则平局。|各プレイヤーの印は対戦ごとに1回。Robinはあなたの札を見ずに確定します。最終同点は引き分けです。|둘 다 경기당 인장 하나가 있어요. Robin은 내 카드를 보지 않고 확정해요. 최종 점수가 같으면 무승부예요.|Mỗi người có một dấu ấn mỗi trận. Robin chốt mà không xem bài bạn. Tổng điểm bằng nhau là hòa.|Keduanya punya satu segel per pertandingan. Robin mengunci tanpa melihat kartu Anda. Skor akhir sama berarti seri.|Ambos tienen un sello por partida. Robin confirma sin ver tus cartas. Si el total es igual, hay empate.|Ambos têm um selo por partida. Robin confirma sem ver suas cartas. Totais iguais dão empate.|Chaque joueur a un sceau par partie. Robin verrouille sans voir vos cartes. Un total égal donne un match nul.
Use each pile's two shared cards. Keep Pile 1 <= Pile 2 <= Pile 3. Pile 3 uses the best three of your five cards.|ใช้ไพ่กลางของแต่ละกองสองใบ ให้กอง 1 ≤ กอง 2 ≤ กอง 3 กอง 3 เลือกสามใบที่ดีที่สุดจากห้าใบของคุณ|使用每组的两张公共牌，保持第1组≤第2组≤第3组。第3组选你的五张中最好的三张。|各組の共通カード2枚を使い、組1≤組2≤組3にします。組3は手札5枚から最良の3枚を使います。|각 더미의 공용 카드 2장을 쓰고 더미 1≤2≤3으로 맞춰요. 더미 3은 내 5장 중 가장 좋은 3장을 써요.|Dùng hai lá chung riêng của mỗi bộ. Giữ bộ 1≤2≤3. Bộ 3 chọn ba lá tốt nhất từ năm lá.|Gunakan dua kartu bersama masing-masing susunan. Susunan 1≤2≤3. Susunan 3 memakai tiga terbaik dari lima kartu Anda.|Usa las dos cartas comunes de cada grupo. Mantén 1≤2≤3. El grupo 3 usa las tres mejores de tus cinco cartas.|Use as duas cartas comuns de cada grupo. Mantenha 1≤2≤3. O grupo 3 usa as três melhores das suas cinco cartas.|Utilisez les deux cartes communes de chaque groupe. Respectez 1≤2≤3. Le groupe 3 utilise les trois meilleures de vos cinq cartes.
Which arrangement is legal?|การจัดไพ่แบบใดถูกกติกา?|哪种排列合法？|どの配置が有効？|어떤 배치가 올바를까요?|Cách xếp nào hợp lệ?|Susunan mana yang sah?|¿Qué distribución es válida?|Qual disposição é válida?|Quelle disposition est valide ?
Pile 1 <= Pile 2 <= Pile 3|กอง 1 ≤ กอง 2 ≤ กอง 3|第1组≤第2组≤第3组|組1≤組2≤組3|더미 1≤더미 2≤더미 3|Bộ 1≤Bộ 2≤Bộ 3|Susunan 1≤2≤3|Grupo 1≤Grupo 2≤Grupo 3|Grupo 1≤Grupo 2≤Grupo 3|Groupe 1≤Groupe 2≤Groupe 3
Put the strongest hand in Pile 1|ให้กอง 1 แข็งที่สุด|第1组放最强的牌|組1を最強にする|더미 1을 가장 강하게|Đặt bài mạnh nhất ở bộ 1|Taruh yang terkuat di susunan 1|Poner lo más fuerte en el grupo 1|Pôr o mais forte no grupo 1|Mettre la main la plus forte dans le groupe 1
Only Pile 3 matters|สนใจเฉพาะกอง 3|只有第3组重要|組3だけが重要|더미 3만 중요|Chỉ bộ 3 quan trọng|Hanya susunan 3 yang penting|Solo importa el grupo 3|Só o grupo 3 importa|Seul le groupe 3 compte
Compare full poker hands, including both shared cards. Equal strength is allowed.|เปรียบเทียบชุดไพ่เต็มรวมไพ่กลางทั้งสองใบ กองที่แข็งเท่ากันใช้ได้|比较包含两张公共牌的完整牌型，允许相同强度。|共通カード2枚を含む完成した役を比較します。同じ強さも有効です。|공용 카드 두 장을 포함한 완성된 패를 비교해요. 강도가 같아도 돼요.|So sánh bài hoàn chỉnh gồm cả hai lá chung. Mạnh bằng nhau vẫn được.|Bandingkan kombinasi lengkap termasuk kedua kartu bersama. Kekuatan sama diperbolehkan.|Compara manos completas, incluidas ambas cartas comunes. Se permite igual fuerza.|Compare mãos completas, incluindo as duas cartas comuns. Forças iguais são permitidas.|Comparez les mains complètes avec les deux cartes communes. Une force égale est permise.
How is Pile 3 scored?|กอง 3 ประเมินไพ่อย่างไร?|第3组如何评定？|組3はどう評価する？|더미 3은 어떻게 평가할까요?|Bộ 3 được tính thế nào?|Bagaimana susunan 3 dinilai?|¿Cómo se evalúa el grupo 3?|Como se avalia o grupo 3?|Comment évalue-t-on le groupe 3 ?
All seven cards count together|ใช้ไพ่ทั้งเจ็ดใบรวมกัน|七张牌全部一起算|7枚すべてを数える|일곱 장 모두 함께 계산|Tính cả bảy lá cùng nhau|Semua tujuh kartu dihitung bersama|Cuentan las siete cartas juntas|Contam todas as sete cartas juntas|Les sept cartes comptent ensemble
Best three of your five + both shared cards|สามใบดีที่สุดจากห้าใบของคุณ + ไพ่กลางสองใบ|你的五张中最好的三张＋两张公共牌|手札5枚の最良3枚＋共通カード2枚|내 5장 중 최선의 3장 + 공용 2장|Ba lá tốt nhất từ năm lá + hai lá chung|Tiga terbaik dari lima + kedua kartu bersama|Tres mejores de tus cinco + las dos comunes|Três melhores das suas cinco + as duas comuns|Trois meilleures de vos cinq + les deux communes
Only your five private cards|ใช้เฉพาะไพ่คุณห้าใบ|只用你的五张手牌|自分の手札5枚のみ|내 카드 다섯 장만|Chỉ năm lá riêng của bạn|Hanya lima kartu pribadi Anda|Solo tus cinco cartas privadas|Só suas cinco cartas privadas|Seulement vos cinq cartes privées
Every pile is evaluated as a five-card poker hand. Pile 3 gives you five private cards to choose three from.|ทุกกองประเมินเป็นโป๊กเกอร์ห้าใบ กอง 3 ให้เลือกสามใบจากไพ่คุณห้าใบ แล้วรวมไพ่กลางสองใบ|每组按五张牌评定。第3组从你的五张手牌选三张，再加两张公共牌。|各組は5枚のポーカー役で評価。組3は手札5枚から3枚を選び、共通カード2枚と合わせます。|모든 더미는 다섯 장의 포커 패로 평가해요. 더미 3은 내 5장 중 3장에 공용 2장을 합쳐요.|Mỗi bộ được tính như bài poker năm lá. Bộ 3 chọn ba trong năm lá riêng rồi thêm hai lá chung.|Setiap susunan dinilai sebagai lima kartu poker. Susunan 3 memilih tiga dari lima kartu pribadi, ditambah dua kartu bersama.|Cada grupo se evalúa con cinco cartas. El grupo 3 elige tres de tus cinco y añade las dos comunes.|Cada grupo é avaliado com cinco cartas. O grupo 3 escolhe três das suas cinco e soma as duas comuns.|Chaque groupe s’évalue sur cinq cartes. Le groupe 3 choisit trois de vos cinq et ajoute les deux communes.
You use your seal on a tied pile. What happens?|ใช้ตราบนกองที่เสมอ จะเกิดอะไรขึ้น?|印记所在牌组打平，会怎样？|印を置いた組が引き分けなら？|인장을 놓은 더미가 비기면?|Dùng dấu ấn ở bộ hòa thì sao?|Apa yang terjadi jika susunan bersegel seri?|¿Qué pasa si el grupo con sello empata?|O que acontece se o grupo com selo empatar?|Que se passe-t-il si le groupe avec sceau fait égalité ?
You get two points|ได้สองแต้ม|你得2分|2点を獲得|2점을 얻어요|Bạn được hai điểm|Anda mendapat dua poin|Ganas dos puntos|Ganha dois pontos|Vous gagnez deux points
The seal returns next hand|ได้ตราคืนมือถัดไป|下一手返还印记|次のハンドで印が戻る|다음 핸드에 인장 반환|Dấu ấn trở lại ván sau|Segel kembali pada tangan berikutnya|Recuperas el sello en la siguiente mano|O selo volta na próxima mão|Le sceau revient à la main suivante
Each player gets half a point; your seal is spent|ได้คนละครึ่งแต้ม ตราของคุณใช้หมดแล้ว|各得半分，你的印记已消耗|各0.5点、印は消費済み|각 0.5점, 인장은 소모돼요|Mỗi người nửa điểm; dấu ấn đã mất|Masing-masing setengah poin; segel habis|Medio punto cada uno; el sello se gasta|Meio ponto para cada; o selo é gasto|Un demi-point chacun ; le sceau est consommé
A seal adds one point only for an outright win. It is used once per match, even if the pile loses or ties.|ตราเพิ่มหนึ่งแต้มเฉพาะชนะ ใช้ได้ครั้งเดียวต่อแมตช์ แม้กองนั้นแพ้หรือเสมอก็ใช้หมด|印记仅在独胜时加1分，每局只能用一次，输或平也会消耗。|印は単独勝利だけ追加1点。対戦につき1回で、負けや引き分けでも消費します。|인장은 단독 승리 때만 1점 추가해요. 경기당 한 번이며 패배나 무승부에도 소모돼요.|Dấu ấn chỉ cộng một điểm khi thắng riêng. Dùng một lần mỗi trận, kể cả khi thua hoặc hòa.|Segel menambah satu poin hanya saat menang mutlak. Sekali per pertandingan, habis meski kalah atau seri.|El sello añade un punto solo al ganar. Se usa una vez por partida, incluso si pierdes o empatas.|O selo adiciona um ponto só ao vencer. Usa-se uma vez por partida, mesmo perdendo ou empatando.|Le sceau ajoute un point seulement en cas de victoire. Un usage par partie, même si le groupe perd ou fait égalité.
What changes at the advanced tables?|โต๊ะขั้นสูงมีอะไรเปลี่ยนไป?|进阶牌桌有什么变化？|上級テーブルでは何が変わる？|고급 테이블에서는 무엇이 달라질까요?|Bàn nâng cao thay đổi gì?|Apa yang berubah di meja lanjutan?|¿Qué cambia en las mesas avanzadas?|O que muda nas mesas avançadas?|Qu’est-ce qui change aux tables avancées ?
Duel points turn into tokens|คะแนนฝึกเปลี่ยนเป็น Token|对决分数变成代币|対戦点がトークンになる|대결 점수가 토큰으로 바뀜|Điểm đấu đổi thành token|Poin duel menjadi token|Los puntos se convierten en fichas|Os pontos viram fichas|Les points deviennent des jetons
Separate token rules, auctions and Call/Fold decisions|มีกติกา Token แยก ระบบประมูล และตัดสินใจตามหรือหมอบ|独立代币规则、竞拍和跟注/弃牌|独立したトークンルール、競売、コール／フォールド|별도 토큰 규칙, 경매, 콜/폴드 선택|Luật token riêng, đấu giá và quyết định theo/bỏ|Aturan token terpisah, lelang, dan ikut/mundur|Reglas de fichas propias, subastas e igualar o retirarse|Regras de fichas próprias, leilões e pagar ou desistir|Règles de jetons séparées, enchères et suivre ou se coucher
Your seal can be purchased|ซื้อตราเพิ่มได้|可以购买印记|印を購入できる|인장을 구매할 수 있음|Có thể mua dấu ấn|Segel bisa dibeli|Puedes comprar sellos|Pode comprar selos|Vous pouvez acheter des sceaux
Advanced tables have their own rules and entry requirements. Duel points never become tokens. Read each table guide before joining.|โต๊ะขั้นสูงมีกติกาและเงื่อนไขเข้าของตัวเอง คะแนนฝึกไม่เปลี่ยนเป็น Token อ่านคำแนะนำก่อนเข้าแต่ละโต๊ะ|进阶牌桌有独立规则和入场条件，练习分数不会变成代币。进入前请阅读指南。|上級テーブルには専用のルールと参加条件があります。練習点はトークンになりません。参加前にガイドを読んでください。|고급 테이블에는 별도 규칙과 입장 조건이 있어요. 연습 점수는 토큰이 되지 않아요. 입장 전에 안내를 읽으세요.|Bàn nâng cao có luật và điều kiện riêng. Điểm tập không đổi thành token. Đọc hướng dẫn trước khi vào.|Meja lanjutan memiliki aturan dan syarat masuk sendiri. Poin latihan tidak menjadi token. Baca panduan sebelum masuk.|Las mesas avanzadas tienen reglas y requisitos propios. Los puntos no se convierten en fichas. Lee la guía antes de entrar.|As mesas avançadas têm regras e requisitos próprios. Os pontos não viram fichas. Leia o guia antes de entrar.|Les tables avancées ont leurs règles et conditions d’entrée. Les points ne deviennent jamais des jetons. Lisez le guide avant d’entrer.
Unable to deal a valid hand. Please try again.|แจกไพ่ที่จัดถูกกติกาไม่สำเร็จ กรุณาลองอีกครั้ง|无法发出有效牌组，请重试。|有効な手札を配れませんでした。再試行してください。|유효한 패를 나누지 못했어요. 다시 시도하세요.|Không chia được bài hợp lệ. Hãy thử lại.|Gagal membagikan kartu yang sah. Coba lagi.|No se pudo repartir una mano válida. Reintenta.|Não foi possível distribuir uma mão válida. Tente novamente.|Impossible de distribuer une main valide. Réessayez.
Invalid five-card hand|ไพ่ห้าใบไม่ถูกต้อง|五张牌无效|5枚の手札が無効です|잘못된 다섯 장 패|Bài năm lá không hợp lệ|Lima kartu tidak sah|Mano de cinco cartas no válida|Mão de cinco cartas inválida|Main de cinq cartes invalide
Invalid seal|เลือกตราไม่ถูกต้อง|印记无效|印が無効です|잘못된 인장|Dấu ấn không hợp lệ|Segel tidak sah|Sello no válido|Selo inválido|Sceau invalide
Seal already spent|ใช้ตราไปแล้ว|印记已消耗|印は使用済み|인장 이미 소모됨|Đã dùng dấu ấn|Segel sudah habis|Sello ya gastado|Selo já gasto|Sceau déjà consommé
Match already complete|แมตช์นี้จบแล้ว|对局已结束|対戦は終了済み|경기 이미 완료|Trận đã kết thúc|Pertandingan sudah selesai|Partida ya terminada|Partida já concluída|Partie déjà terminée
`;
