import type { Language } from './translate'

/** Short playful messages shown only while a new Tier D table is being dealt. */
export const TIER_D_LOADING_TAUNTS: Record<Language, readonly string[]> = {
  en: ['THIS ROUND IS BRUTAL. GOOD LUCK.', 'SAVE SOMETHING FOR THE FINAL MATCH.', 'CLEAR THIS LEVEL? THAT IS IMPRESSIVE.', 'EVEN EINSTEIN WOULD PAUSE HERE.', 'THE AI HAS BEEN PRACTICING. HAVE YOU?', 'DO NOT LET G3 STEAL THE SHOW.', 'YOUR CARDS LOOK CONFIDENT. ARE YOU?', 'A PERFECT PLAN IS ONE SWAP AWAY.', 'NO PRESSURE. THE TABLE IS WATCHING.', 'TIME TO MAKE THE AI RECONSIDER.'],
  th: ['รอบนี้โหดมากนะ ขอให้โชคดี', 'เก็บของดีไว้แมตช์สุดท้ายด้วยล่ะ', 'เคลียร์เลเวลนี้ได้... แน่มาก ๆ', 'แม้แต่ไอน์สไตน์ก็ยังต้องคิดหนัก', 'AI ซ้อมมาแล้ว ลุงพร้อมหรือยัง?', 'อย่าให้ G3 ขโมยซีนไปนะ', 'ไพ่ดูมั่นใจ แล้วลุงล่ะมั่นใจไหม?', 'แผนที่ดีอาจห่างแค่การสลับใบเดียว', 'ไม่กดดันนะ... ทั้งโต๊ะกำลังมองอยู่', 'ถึงเวลาทำให้ AI ต้องคิดใหม่แล้ว'],
  zh: ['这一局很硬，祝你好运。', '好牌留给最后一场。', '能通关这关，真的很强。', '连爱因斯坦也得认真想想。', 'AI 已经练过了，你呢？', '别让 G3 抢走风头。', '你的牌看起来很自信，你呢？', '完美计划也许只差一次换牌。', '别紧张，全桌都在看。', '该让 AI 重新思考了。'],
  ja: ['このラウンドは手強い。幸運を。', '最後のマッチに強い札を残して。', 'このレベルをクリアできたら本物だ。', 'アインシュタインでも考え込むかも。', 'AI は練習済み。あなたは？', 'G3 に主役を奪わせないで。', 'カードは自信満々。あなたは？', '完璧な作戦は一回の交換の先にある。', 'プレッシャーはなし。テーブルが見ている。', 'AI に考え直させる時間だ。'],
  ko: ['이번 라운드는 정말 어렵습니다. 행운을 빌어요.', '마지막 매치를 위해 좋은 패를 남겨 두세요.', '이 레벨을 깨면 정말 대단합니다.', '아인슈타인도 여기선 고민할 거예요.', 'AI는 연습했습니다. 당신은요?', 'G3에게 주인공 자리를 뺏기지 마세요.', '카드는 자신 있어 보이네요. 당신은요?', '완벽한 계획은 카드 한 번 교체 차이입니다.', '부담 없어요. 테이블이 보고 있을 뿐이에요.', 'AI가 다시 생각하게 만들 시간입니다.'],
  vi: ['Ván này khó lắm. Chúc may mắn.', 'Hãy để dành bài mạnh cho trận cuối.', 'Qua được màn này thì thật đáng nể.', 'Ngay cả Einstein cũng phải suy nghĩ.', 'AI đã luyện tập rồi, còn bạn?', 'Đừng để G3 chiếm hết ánh đèn.', 'Bài của bạn có vẻ tự tin. Còn bạn?', 'Kế hoạch hoàn hảo có thể chỉ cách một lần đổi bài.', 'Không áp lực đâu. Cả bàn chỉ đang nhìn thôi.', 'Đã đến lúc khiến AI phải nghĩ lại.'],
  id: ['Ronde ini brutal. Semoga beruntung.', 'Simpan kartu bagus untuk pertandingan terakhir.', 'Bisa menuntaskan level ini? Hebat sekali.', 'Einstein pun mungkin perlu berpikir keras.', 'AI sudah berlatih. Kamu sudah?', 'Jangan biarkan G3 mencuri perhatian.', 'Kartumu terlihat percaya diri. Kamu juga?', 'Rencana sempurna mungkin hanya satu tukar kartu lagi.', 'Tanpa tekanan. Meja hanya sedang memperhatikan.', 'Saatnya membuat AI berpikir ulang.'],
  es: ['Esta ronda es brutal. Buena suerte.', 'Guarda algo fuerte para la partida final.', '¿Superar este nivel? Eso sí que impresiona.', 'Hasta Einstein tendría que pensarlo.', 'La IA ha practicado. ¿Y tú?', 'No dejes que G3 se robe el protagonismo.', 'Tus cartas parecen seguras. ¿Tú también?', 'Un plan perfecto puede estar a un cambio.', 'Sin presión. La mesa te está mirando.', 'Es hora de hacer que la IA lo reconsidere.'],
  pt: ['Esta rodada é brutal. Boa sorte.', 'Guarde algo forte para a partida final.', 'Limpar este nível? Isso é impressionante.', 'Até Einstein pensaria bastante aqui.', 'A IA treinou. E você?', 'Não deixe G3 roubar a cena.', 'Suas cartas parecem confiantes. E você?', 'Um plano perfeito pode estar a uma troca.', 'Sem pressão. A mesa está observando.', 'Hora de fazer a IA pensar de novo.'],
  fr: ['Cette manche est brutale. Bonne chance.', 'Gardez du solide pour le dernier match.', 'Finir ce niveau ? Très impressionnant.', 'Même Einstein réfléchirait ici.', "L’IA s’est entraînée. Et vous ?", 'Ne laissez pas G3 voler la vedette.', 'Vos cartes ont confiance. Et vous ?', 'Un plan parfait est peut-être à un échange.', 'Aucune pression. La table vous regarde.', 'Il est temps de faire douter l’IA.'],
}
