// authGuard.ts
// ตรวจว่า display_name เป็นชื่อ auto-generated จาก DB trigger ตอน signup หรือยัง
// ต้องตั้งชื่อเองก่อนถึงจะเข้า (home)/game ได้ — ใช้ร่วมกันทั้ง (home)/_layout.tsx และ game/_layout.tsx
// (เดิม logic นี้ก็อปกันเป๊ะๆ ทั้ง 2 ไฟล์ — รวมมาไว้ที่เดียวกันแทน)

// pattern ของชื่อ auto-generated จาก DB trigger (สร้างบน Supabase dashboard โดยตรง ไม่ได้ commit
// อยู่ใน repo นี้) — ถ้า trigger เปลี่ยนรูปแบบในอนาคต แก้ตรงนี้จุดเดียวพอ
// Patch (2026-07-17): เดิม 8 hex ("user_" + 8 = 13 ตัวอักษร) เกิน limit ใหม่ (≤9 ตัวอักษรทั้งระบบ) —
// เปลี่ยนเป็น 4 hex ("user_" + 4 = 9 ตัวอักษรพอดี) ต้องแก้ trigger ฝั่ง Supabase ให้ตรงกันด้วย (ดู SQL
// ที่แนบให้ลุงรันเอง — เขียนเองไม่ได้เพราะ trigger ไม่ได้ commit อยู่ใน repo นี้)
const AUTO_GENERATED_NAME_PATTERN = /^user_[a-f0-9]{4}$/

export function isAutoGeneratedDisplayName(displayName: string | null | undefined): boolean {
  return displayName ? AUTO_GENERATED_NAME_PATTERN.test(displayName) : true
}

export function needsProfileSetup(displayName: string | null | undefined): boolean {
  return !displayName || isAutoGeneratedDisplayName(displayName)
}
