// app/game/_layout.tsx
// Auth Guard สำหรับทุกหน้าใน group game
// ต้องมี session + display_name ถึงจะเข้าได้ (กันการเข้าตรงผ่าน URL)
import { Stack, Redirect } from 'expo-router'
import { useAuthStore } from '../../src/store/authStore'
import { View, ActivityIndicator } from 'react-native'

export default function GameLayout() {
  const { isInitialized, session, profile } = useAuthStore()

  if (!isInitialized) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#0F2418' }}>
        <ActivityIndicator color="#FFD76A" />
      </View>
    )
  }

  if (!session) return <Redirect href="/(auth)/login" />
  const isAutoGeneratedName = profile?.display_name
    ? /^user_[a-f0-9]{8}$/.test(profile.display_name)
    : true
  if (!profile?.display_name || isAutoGeneratedName) return <Redirect href="/(auth)/setup-profile" />

  return <Stack screenOptions={{ headerShown: false }} />
}
