import React, { useEffect, useRef } from 'react'
import { Animated, Image, ImageSourcePropType, StyleSheet, Text, TouchableOpacity, View } from 'react-native'

const TROPHIES: Record<string, ImageSourcePropType> = {
  Bronze: require('../../../assets/league/Bronze League Trophy.png'), Silver: require('../../../assets/league/Silver League Trophy.png'),
  Gold: require('../../../assets/league/Gold League Trophy.png'), Platinum: require('../../../assets/league/Platinum League Trophy.png'),
  Diamond: require('../../../assets/league/Diamond League Trophy.png'), Elite: require('../../../assets/league/Elite League Trophy.png'),
  Master: require('../../../assets/league/Master League Trophy.png'), Grandmaster: require('../../../assets/league/Grandmaster League Trophy.png'),
  Champion: require('../../../assets/league/Champion League Trophy.png'), Legend: require('../../../assets/league/Legend League Trophy.png'),
}
const LEAGUES = Object.keys(TROPHIES)
function leagueFor(level:number) { const index=Math.floor((level-1)/50); const name=LEAGUES[index]??`League ${index+1}`; const start=index*50+1; return {name,start,end:start+49,trophy:TROPHIES[name]??TROPHIES.Legend} }

export function TierDSoloResult({ level, playerScore, opponentScore, streak, phase, rankedEnabled, level500Unlocked, playerWon, reward, rewardQuantity=1, canWatchAd=false, watchingAd=false, elapsedMs, personalBestMs, onWatchAd, onNext }: { level:number; playerScore:number; opponentScore:number; streak:number; phase:'relax'|'ranked'; rankedEnabled:boolean; level500Unlocked:boolean; playerWon:boolean; reward?:string; rewardQuantity?:number; canWatchAd?:boolean; watchingAd?:boolean; elapsedMs?:number; personalBestMs?:number; onWatchAd?:()=>void; onNext:()=>void }) {
  const sparkle=useRef(new Animated.Value(0)).current; const league=leagueFor(level); const levelInLeague=level-league.start+1; const remaining=Math.max(0,league.end-level)
  useEffect(()=>{if(!playerWon)return; const loop=Animated.loop(Animated.sequence([Animated.timing(sparkle,{toValue:1,duration:900,useNativeDriver:true}),Animated.timing(sparkle,{toValue:0,duration:900,useNativeDriver:true})]));loop.start();return()=>loop.stop()},[playerWon,sparkle])
  if(!playerWon)return <View style={s.panel}><Text style={s.title}>LEVEL {level} RESULT</Text><Text style={s.loss}>KEEP TRAINING — LEVEL {level} REMAINS</Text><Text style={s.text}>WIN STREAK RESET · {phase.toUpperCase()}</Text><TouchableOpacity style={s.next} onPress={onNext}><Text style={s.nextText}>TRY AGAIN</Text></TouchableOpacity></View>
  return <View style={s.panel}><Text style={s.clear}>LEVEL {level} CLEARED!</Text><View style={s.trophyWrap}><Animated.View style={[s.sparkle,{opacity:sparkle,transform:[{scale:sparkle.interpolate({inputRange:[0,1],outputRange:[.75,1.35]})}]}]}><Text style={s.sparkleText}>✦ ✧ ✦ ✧ ✦</Text></Animated.View><Image source={league.trophy} resizeMode="contain" style={s.trophy}/></View><Text style={s.league}>{league.name.toUpperCase()} LEAGUE</Text><Text style={s.finalScore}>FINAL SCORE  YOU {playerScore} — {opponentScore} AI</Text><Text style={s.maxScore}>3 MATCHES · MAX 42 POINTS · SWEEP +5</Text><Text style={s.text}>WIN STREAK {streak} · {phase.toUpperCase()}</Text>{typeof elapsedMs==='number'?<Text style={s.time}>LEVEL TIME {formatTime(elapsedMs)} · PERSONAL BEST {formatTime(personalBestMs??elapsedMs)}</Text>:null}{reward?<><Text style={s.reward}>REWARD: ×{rewardQuantity} {reward.replaceAll('_',' ').toUpperCase()}</Text>{canWatchAd?<TouchableOpacity disabled={watchingAd} style={[s.adButton,watchingAd&&s.adDisabled]} onPress={onWatchAd}><Text style={s.adText}>{watchingAd?'VERIFYING AD…':'WATCH AD · GET ×2'}</Text></TouchableOpacity>:rewardQuantity===2?<Text style={s.vipReward}>VIP BONUS · ×2 AUTOMATIC</Text>:null}</>:null}<View style={s.progressBox}><View style={s.progressLabels}><Text style={s.progressText}>LEAGUE PROGRESS</Text><Text style={s.progressText}>{remaining} LEVEL{remaining===1?'':'S'} LEFT</Text></View><View style={s.track}><View style={[s.fill,{width:`${Math.min(100,(levelInLeague/50)*100)}%`}]} /></View><Text style={s.range}>LV. {league.start} — {league.end} · {levelInLeague}/50</Text></View>{phase==='ranked' && rankedEnabled ? <Text style={s.text}>RANKED LEADERBOARD READY</Text> : null}{level500Unlocked ? <Text style={s.unlock}>LEVEL 500 CLEARED{`\n`}TABLE PLAY UNLOCKED{`\n`}+10,000 TOKENS</Text> : null}<TouchableOpacity style={s.next} onPress={onNext}><Text style={s.nextText}>NEXT LEVEL</Text></TouchableOpacity></View>
}
const formatTime=(ms:number)=>{const sec=Math.floor(ms/1000);return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
const s=StyleSheet.create({panel:{backgroundColor:'rgba(12,35,23,.97)',borderColor:'#FFD76A',borderWidth:1,borderRadius:14,padding:18,gap:8,alignItems:'center'},title:{color:'#FFD76A',fontWeight:'900',fontSize:18},clear:{color:'#FFD76A',fontWeight:'900',fontSize:26,letterSpacing:1,textShadowColor:'#b76d00',textShadowRadius:12},loss:{color:'#ffb0b0',fontWeight:'900'},text:{color:'#F5F2E8'},time:{color:'#9ddaff',fontSize:11,fontWeight:'800'},reward:{color:'#8DFFB5',fontSize:11,fontWeight:'900'},vipReward:{color:'#FFD76A',fontSize:10,fontWeight:'900'},adButton:{alignSelf:'stretch',borderWidth:1,borderColor:'#8DFFB5',borderRadius:8,padding:10,alignItems:'center',backgroundColor:'rgba(141,255,181,.12)'},adDisabled:{opacity:.55},adText:{color:'#8DFFB5',fontWeight:'900',fontSize:11},league:{color:'#FFD76A',fontWeight:'900',fontSize:16},finalScore:{color:'#F5F2E8',fontWeight:'900',fontSize:17},maxScore:{color:'#8DFFB5',fontSize:10,fontWeight:'800'},trophyWrap:{height:116,width:170,alignItems:'center',justifyContent:'center'},trophy:{width:112,height:112,zIndex:2},sparkle:{position:'absolute',alignItems:'center',justifyContent:'center',zIndex:3},sparkleText:{color:'#fff0a8',fontSize:34,textShadowColor:'#FFD76A',textShadowRadius:18},progressBox:{alignSelf:'stretch',backgroundColor:'rgba(4,14,9,.75)',borderRadius:10,borderWidth:1,borderColor:'rgba(255,215,106,.45)',padding:10,gap:6},progressLabels:{flexDirection:'row',justifyContent:'space-between'},progressText:{color:'#F5F2E8',fontWeight:'800',fontSize:10},track:{height:10,borderRadius:5,backgroundColor:'#0b1d13',borderWidth:1,borderColor:'#426a55',overflow:'hidden'},fill:{height:'100%',backgroundColor:'#57c7ff',borderRadius:5,shadowColor:'#57c7ff',shadowOpacity:1,shadowRadius:8},range:{color:'#b9d5e3',fontSize:10,textAlign:'center'},unlock:{color:'#8DFFB5',fontWeight:'900',textAlign:'center',marginVertical:8},next:{alignSelf:'stretch',backgroundColor:'#FFD76A',borderRadius:8,padding:12,alignItems:'center'},nextText:{fontWeight:'900',color:'#163A25'}})
