import React, { useMemo, useState } from 'react'
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import Card, { type Suit, type Value } from './Card'
import { GameActionButton } from '../ui/GameActionButton'

export type TierDAnalysisSnapshot={matchNumber:1|2|3;actualScore:number;bestScore:number;actualWins:number;bestWins:number;actualMissionCount:number;bestMissionCount:number;actualCombo:number;bestCombo:number;pile:{actual:number[];best:number[]};community?:{pile1:string[];pile2:string[];pile3:string[]};actual?:{pile1:string[];pile2:string[];pile3:string[]};best?:{pile1:string[];pile2:string[];pile3:string[]}}
const decode=(key:string)=>({suit:({s:'spade',h:'heart',d:'diamond',c:'club'}[key.slice(-1)]??'spade') as Suit,value:key.slice(0,-1).toLowerCase() as Value})
const pileKeys = ['pile1','pile2','pile3'] as const
function Cards({cards}:{cards:string[]}){return <View style={s.cards}>{cards.map((key,index)=>{const card=decode(key);return <Card key={`${key}-${index}`} variant="face" suit={card.suit} value={card.value} width={31} height={45} style={index?{marginLeft:-10}:undefined}/>})}</View>}
function Arrangement({title,piles}:{title:string;piles:{pile1:string[];pile2:string[];pile3:string[]}}){return <View style={s.arrangement}><Text style={s.section}>{title}</Text>{pileKeys.map((key,index)=><View key={key} style={s.pile}><Text style={s.pileLabel}>G{index+1}</Text><Cards cards={piles[key]}/></View>)}</View>}

export function TierDVIPAnalysis({level,snapshots,onBack,onNext}:{level:number;snapshots:TierDAnalysisSnapshot[];onBack:()=>void;onNext:()=>void}){
 const [selected,setSelected]=useState(()=>snapshots.reduce((best,current)=>current.bestScore-current.actualScore>best.bestScore-best.actualScore?current:best,snapshots[0]))
 const [tab,setTab]=useState<'best'|'why'>('best'); const difference=selected.bestScore-selected.actualScore
 const actual=selected.actual;const best=selected.best
 const meaningfulAlternative=selected.bestWins>selected.actualWins&&selected.bestWins!==selected.bestScore-selected.actualScore
 return <View style={s.root}><Text style={s.title}>VIP ANALYSIS — LEVEL {level}</Text><View style={s.summary}><Summary label="YOUR SCORE" value={selected.actualScore}/><Summary label="BEST POSSIBLE" value={selected.bestScore}/><Summary label="DIFFERENCE" value={`+${difference}`}/></View><View style={s.selector}>{snapshots.map(snapshot=><Pressable key={snapshot.matchNumber} onPress={()=>setSelected(snapshot)} style={[s.match,snapshot.matchNumber===selected.matchNumber&&s.matchActive]}><Text style={s.matchText}>MATCH {snapshot.matchNumber}</Text></Pressable>)}</View><View style={s.tabs}><Pressable onPress={()=>setTab('best')} style={[s.tab,tab==='best'&&s.tabActive]}><Text style={s.tabText}>BEST ARRANGEMENT</Text></Pressable><Pressable onPress={()=>setTab('why')} style={[s.tab,tab==='why'&&s.tabActive]}><Text style={s.tabText}>WHY THIS IS BETTER</Text></Pressable></View><ScrollView contentContainerStyle={s.content}>{tab==='best'&&actual&&best?<><Arrangement title="YOUR ARRANGEMENT" piles={actual}/><Arrangement title="BEST ARRANGEMENT" piles={best}/><Text style={s.compare}>Your {selected.actualScore} pts → Best {selected.bestScore} pts</Text><Text style={s.gain}>+{difference} POSSIBLE</Text></>:<Why snapshot={selected} alternative={meaningfulAlternative}/>}</ScrollView><View style={s.actions}><GameActionButton fitContent label="BACK TO LEVEL CLEARED" variant="secondary" onPress={onBack}/><GameActionButton fitContent label="NEXT LEVEL" onPress={onNext}/></View></View>
}
function Summary({label,value}:{label:string;value:string|number}){return <View style={s.summaryCell}><Text style={s.summaryLabel}>{label}</Text><Text style={s.summaryValue}>{value}</Text></View>}
function Why({snapshot,alternative}:{snapshot:TierDAnalysisSnapshot;alternative:boolean}){const rows=pileKeys.map((_,index)=>({label:`G${index+1}`,from:snapshot.pile.actual[index]??0,to:snapshot.pile.best[index]??0})).filter(row=>row.from!==row.to);if(snapshot.actualCombo!==snapshot.bestCombo)rows.push({label:'COMBO',from:snapshot.actualCombo,to:snapshot.bestCombo});if(snapshot.actualMissionCount!==snapshot.bestMissionCount)rows.push({label:'MISSION',from:snapshot.actualMissionCount,to:snapshot.bestMissionCount});return <View style={s.why}>{rows.map(row=><View key={row.label} style={s.whyRow}><Text style={s.whyLabel}>{row.label}</Text><Text style={s.whyValue}>{row.from} → {row.to}</Text><Text style={s.whyGain}>{row.to-row.from>=0?'+':''}{row.to-row.from}</Text></View>)}<Text style={s.net}>NET GAIN +{snapshot.bestScore-snapshot.actualScore}</Text>{alternative?<View style={s.note}><Text style={s.noteText}>A higher-win route is also available for this match.</Text></View>:null}</View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#071108',padding:18,paddingTop:48,gap:12},title:{color:'#FFD76A',fontWeight:'900',fontSize:17,textAlign:'center',letterSpacing:.6},summary:{flexDirection:'row',borderWidth:1,borderColor:'rgba(255,215,106,.55)',borderRadius:10,backgroundColor:'rgba(22,35,24,.9)'},summaryCell:{flex:1,alignItems:'center',paddingVertical:10},summaryLabel:{color:'#9ddaff',fontSize:8,fontWeight:'900'},summaryValue:{color:'#F5F2E8',fontWeight:'900',fontSize:21,marginTop:2},selector:{flexDirection:'row',gap:6},match:{flex:1,borderWidth:1,borderColor:'#49634e',borderRadius:7,paddingVertical:8,alignItems:'center'},matchActive:{borderColor:'#FFD76A',backgroundColor:'rgba(255,215,106,.14)'},matchText:{color:'#F5F2E8',fontWeight:'900',fontSize:9},tabs:{flexDirection:'row',borderBottomWidth:1,borderColor:'#48614b'},tab:{flex:1,paddingVertical:9,alignItems:'center'},tabActive:{borderBottomWidth:2,borderColor:'#FFD76A'},tabText:{color:'#FFD76A',fontSize:9,fontWeight:'900'},content:{paddingVertical:4,gap:12},actions:{gap:8},arrangement:{borderWidth:1,borderColor:'rgba(255,215,106,.35)',borderRadius:10,padding:10,gap:7,backgroundColor:'rgba(10,29,18,.82)'},section:{color:'#FFD76A',fontWeight:'900',fontSize:11},pile:{flexDirection:'row',alignItems:'center',gap:10},pileLabel:{color:'#9ddaff',fontWeight:'900',width:18},cards:{flexDirection:'row',minHeight:46,alignItems:'center'},compare:{textAlign:'center',color:'#F5F2E8',fontWeight:'800'},gain:{textAlign:'center',color:'#8DFFB5',fontWeight:'900',fontSize:16},why:{gap:8,borderWidth:1,borderColor:'rgba(255,215,106,.35)',borderRadius:10,padding:12,backgroundColor:'rgba(10,29,18,.82)'},whyRow:{flexDirection:'row',alignItems:'center'},whyLabel:{color:'#FFD76A',fontWeight:'900',width:70},whyValue:{color:'#F5F2E8',flex:1,fontWeight:'800'},whyGain:{color:'#8DFFB5',fontWeight:'900'},net:{color:'#8DFFB5',fontSize:18,fontWeight:'900',textAlign:'center',marginTop:8},note:{marginTop:6,padding:8,borderRadius:7,backgroundColor:'rgba(157,218,255,.12)'},noteText:{color:'#9ddaff',fontSize:10,fontWeight:'800',textAlign:'center'}})
