import React, { useEffect, useRef } from 'react'
import { Animated, Image, ImageSourcePropType, StyleSheet, Text, TouchableOpacity, View } from 'react-native'

const TROPHIES: Record<string, ImageSourcePropType> = {
  Bronze: require('../../../assets/league/Bronze League Trophy.png'), Silver: require('../../../assets/league/Silver League Trophy.png'),
  Gold: require('../../../assets/league/Gold League Trophy.png'), Platinum: require('../../../assets/league/Platinum League Trophy.png'),
  Diamond: require('../../../assets/league/Diamond League Trophy.png'), Elite: require('../../../assets/league/Elite League Trophy.png'),
  Master: require('../../../assets/league/Master League Trophy.png'), Grandmaster: require('../../../assets/league/Grandmaster League Trophy.png'),
  Champion: require('../../../assets/league/Champion League Trophy.png'), Legend: require('../../../assets/league/Legend League Trophy.png'),
}
const LEAGUES = [
  {name:'Bronze',start:1,end:50},{name:'Silver',start:51,end:100},{name:'Gold',start:101,end:150},
  {name:'Platinum',start:151,end:200},{name:'Diamond',start:201,end:250},{name:'Elite',start:251,end:350},
  {name:'Master',start:351,end:500},{name:'Grandmaster',start:501,end:700},{name:'Legend',start:701,end:1000},
  {name:'Mythic',start:1001,end:1500},
] as const
function leagueFor(level:number) { const definition=LEAGUES.find(league=>level>=league.start&&level<=league.end)??LEAGUES[LEAGUES.length-1];const endless=level>1500;return {...definition,name:endless?'Mythic Endless':definition.name,trophy:TROPHIES[definition.name]??TROPHIES.Champion,endless} }
/** Tier D's presentation difficulty rises linearly from Lv.1 (40) to Lv.1500 (98). */
function difficultyFor(level:number){const bounded=Math.min(1500,Math.max(1,level));return 40+((bounded-1)*58/1499)}
/** A celebratory estimate, deliberately capped and stable for a given clear result. */
function estimatedIq(level:number,elapsedMs?:number){const difficulty=difficultyFor(level);const pace=Math.max(0,Math.min(1,1-((elapsedMs??300000)/300000)));const variation=(Math.sin(level*12.9898+(elapsedMs??0)*.000017)*.5+.5)*2.4-1.2;return Math.max(140,Math.min(220,140+((difficulty-40)/58)*40+pace*40+variation))}

export function TierDSoloResult({ level, playerScore, opponentScore, streak, level500Unlocked, playerWon, openChallengePassed=true, reward, rewardQuantity=1, canWatchAd=false, watchingAd=false, competition, elapsedMs, personalBestMs, onWatchAd, onRanking, onNext }: { level:number; playerScore:number; opponentScore:number; streak:number; level500Unlocked:boolean; playerWon:boolean; openChallengePassed?:boolean; reward?:string; rewardQuantity?:number; canWatchAd?:boolean; watchingAd?:boolean; competition?:{rank:number;items:string[];awarded:boolean}; elapsedMs?:number; personalBestMs?:number; onWatchAd?:()=>void; onRanking?:()=>void; onNext:()=>void }) {
  const sparkle=useRef(new Animated.Value(0)).current; const league=leagueFor(level); const levelInLeague=level-league.start+1; const span=league.end-league.start+1; const remaining=Math.max(0,league.end-level); const difficulty=difficultyFor(level); const iq=estimatedIq(level,elapsedMs)
  useEffect(()=>{if(!playerWon)return; const loop=Animated.loop(Animated.sequence([Animated.timing(sparkle,{toValue:1,duration:900,useNativeDriver:true}),Animated.timing(sparkle,{toValue:0,duration:900,useNativeDriver:true})]));loop.start();return()=>loop.stop()},[playerWon,sparkle])
  if(!playerWon)return <View style={s.panel}><Text style={s.title}>LEVEL {level} RESULT</Text><Text style={s.loss}>LEVEL {level} REMAINS</Text><Text style={s.difficulty}>DIFFICULTY {difficulty.toFixed(1)} / 100</Text><Text style={s.finalScore}>YOU {playerScore} — {opponentScore} HIGHEST AI</Text>{!openChallengePassed?<Text style={s.challengeFail}>OPEN CHALLENGE FAILED · G1+G2+G3 SWEEP REQUIRED</Text>:null}<Text style={s.text}>WIN STREAK {streak} · RETRY GENERATES 3 NEW MATCHES</Text>{onRanking?<TouchableOpacity style={s.ranking} onPress={onRanking}><Text style={s.rankingText}>LEAGUE TOP 20</Text></TouchableOpacity>:null}<TouchableOpacity style={s.next} onPress={onNext}><Text style={s.nextText}>TRY AGAIN</Text></TouchableOpacity></View>
  return <View style={s.panel}><Text style={s.leagueHero}>{league.name.toUpperCase()} LEAGUE</Text><View style={s.trophyWrap}><Animated.View style={[s.sparkle,{opacity:sparkle,transform:[{scale:sparkle.interpolate({inputRange:[0,1],outputRange:[.75,1.35]})}]}]}><Text style={s.sparkleText}>✦ ✧ ✦ ✧ ✦</Text></Animated.View><Image source={league.trophy} resizeMode="contain" style={s.trophy}/></View><Text style={s.clear}>LEVEL {level} CLEARED!</Text><Text style={s.difficulty}>DIFFICULTY {difficulty.toFixed(1)} / 100</Text><Text style={s.iq}>EST. IQ {iq.toFixed(1)}</Text><Text style={s.finalScore}>YOU {playerScore} — {opponentScore} HIGHEST AI</Text><Text style={s.maxScore}>3 MATCH TOTAL · TIES FAVOR YOU</Text><Text style={s.text}>WIN STREAK {streak}</Text>{typeof elapsedMs==='number'?<Text style={s.time}>LEVEL TIME {formatTime(elapsedMs)} · PERSONAL BEST {formatTime(personalBestMs??elapsedMs)}</Text>:null}{competition?<View style={s.competition}><Text style={s.competitionTitle}>COMPETITION COMPLETE · RANK #{competition.rank}</Text><Text style={s.competitionReward}>RANK REWARD: {competition.items.map(item=>item.replaceAll('_',' ').toUpperCase()).join(' · ')}</Text></View>:null}{reward?<><Text style={s.reward}>REWARD: ×{rewardQuantity} {reward.replaceAll('_',' ').toUpperCase()}</Text>{canWatchAd?<TouchableOpacity disabled={watchingAd} style={[s.adButton,watchingAd&&s.adDisabled]} onPress={onWatchAd}><Text style={s.adText}>{watchingAd?'VERIFYING AD…':'WATCH AD · GET ×2'}</Text></TouchableOpacity>:rewardQuantity===2?<Text style={s.vipReward}>VIP BONUS · ×2 AUTOMATIC</Text>:null}</>:null}{!league.endless?<View style={s.progressBox}><View style={s.progressLabels}><Text style={s.progressText}>LEAGUE PROGRESS</Text><Text style={s.progressText}>{remaining} LEVEL{remaining===1?'':'S'} LEFT</Text></View><View style={s.track}><View style={[s.fill,{width:`${Math.min(100,(levelInLeague/span)*100)}%`}]} /></View><Text style={s.range}>LV. {league.start} — {league.end} · {levelInLeague}/{span}</Text></View>:<Text style={s.text}>MYTHIC ENDLESS · LV. {level}</Text>}{level500Unlocked ? <Text style={s.unlock}>LEVEL 500 CLEARED{`\n`}TIER B UNLOCKED</Text> : null}{onRanking?<TouchableOpacity style={s.ranking} onPress={onRanking}><Text style={s.rankingText}>LEAGUE TOP 20</Text></TouchableOpacity>:null}<TouchableOpacity style={s.next} onPress={onNext}><Text style={s.nextText}>NEXT LEVEL</Text></TouchableOpacity></View>
}
const formatTime=(ms:number)=>{const sec=Math.floor(ms/1000);return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
const s=StyleSheet.create({panel:{backgroundColor:'rgba(12,35,23,.97)',borderColor:'#FFD76A',borderWidth:1,borderRadius:14,padding:18,gap:8,alignItems:'center'},title:{color:'#FFD76A',fontWeight:'900',fontSize:18},clear:{color:'#FFD76A',fontWeight:'900',fontSize:26,letterSpacing:1,textShadowColor:'#b76d00',textShadowRadius:12},leagueHero:{color:'#FFF0A8',fontWeight:'900',fontSize:32,letterSpacing:1.3,textShadowColor:'#b76d00',textShadowRadius:14},loss:{color:'#ffb0b0',fontWeight:'900'},difficulty:{color:'#9ddaff',fontWeight:'900',fontSize:13,letterSpacing:.5},iq:{color:'#FFD76A',fontWeight:'900',fontSize:18,letterSpacing:1,textShadowColor:'#a56200',textShadowRadius:8},competition:{alignSelf:'stretch',padding:9,borderRadius:8,borderWidth:1,borderColor:'rgba(255,215,106,.62)',backgroundColor:'rgba(120,78,7,.25)',gap:3},competitionTitle:{color:'#FFD76A',fontWeight:'900',textAlign:'center'},competitionReward:{color:'#F5F2E8',fontSize:10,fontWeight:'800',textAlign:'center'},challengeFail:{color:'#ffb0b0',fontSize:11,fontWeight:'900',textAlign:'center'},text:{color:'#F5F2E8'},time:{color:'#9ddaff',fontSize:11,fontWeight:'800'},reward:{color:'#8DFFB5',fontSize:11,fontWeight:'900'},vipReward:{color:'#FFD76A',fontSize:10,fontWeight:'900'},adButton:{alignSelf:'stretch',borderWidth:1,borderColor:'#8DFFB5',borderRadius:8,padding:10,alignItems:'center',backgroundColor:'rgba(141,255,181,.12)'},adDisabled:{opacity:.55},adText:{color:'#8DFFB5',fontWeight:'900',fontSize:11},league:{color:'#FFD76A',fontWeight:'900',fontSize:16},finalScore:{color:'#F5F2E8',fontWeight:'900',fontSize:17},maxScore:{color:'#8DFFB5',fontSize:10,fontWeight:'800'},trophyWrap:{height:116,width:170,alignItems:'center',justifyContent:'center'},trophy:{width:112,height:112,zIndex:2},sparkle:{position:'absolute',alignItems:'center',justifyContent:'center',zIndex:3},sparkleText:{color:'#fff0a8',fontSize:34,textShadowColor:'#FFD76A',textShadowRadius:18},progressBox:{alignSelf:'stretch',backgroundColor:'rgba(4,14,9,.75)',borderRadius:10,borderWidth:1,borderColor:'rgba(255,215,106,.45)',padding:10,gap:6},progressLabels:{flexDirection:'row',justifyContent:'space-between'},progressText:{color:'#F5F2E8',fontWeight:'800',fontSize:10},track:{height:10,borderRadius:5,backgroundColor:'#0b1d13',borderWidth:1,borderColor:'#426a55',overflow:'hidden'},fill:{height:'100%',backgroundColor:'#57c7ff',borderRadius:5,shadowColor:'#57c7ff',shadowOpacity:1,shadowRadius:8},range:{color:'#b9d5e3',fontSize:10,textAlign:'center'},unlock:{color:'#8DFFB5',fontWeight:'900',textAlign:'center',marginVertical:8},ranking:{alignSelf:'stretch',borderWidth:1,borderColor:'#9ddaff',borderRadius:8,padding:10,alignItems:'center',backgroundColor:'rgba(87,199,255,.10)'},rankingText:{fontWeight:'900',color:'#9ddaff'},next:{alignSelf:'stretch',backgroundColor:'#FFD76A',borderRadius:8,padding:12,alignItems:'center'},nextText:{fontWeight:'900',color:'#163A25'}})
