import React, { useEffect, useRef, useState } from 'react'
import { Animated, Platform, StyleSheet, Text, View } from 'react-native'
import { Image as ExpoImage } from 'expo-image'
import Svg, { Path, Rect } from 'react-native-svg'
import { GameActionButton } from '../ui/GameActionButton'

const LOTUS_VICTORY = require('../../../assets/fx/level_cleared_lotus.webp')
const PRAISES = ['Great!', 'Cool!', 'Nice!', 'Excellent!', 'Bravo!'] as const
const NEXT_LEVEL_MESSAGES = ['ด่านที่แล้วคุณทำได้ดีมาก', 'ฟอร์มกำลังมาเลย ลุยต่อ!', 'เล่นได้เฉียบมาก ด่านต่อไปพร้อมแล้ว', 'ชัยชนะนี้เป็นของคุณ'] as const
const NEXT_LEVEL_DIFFICULTIES = ['ด่านโหด', 'โคตรหิน', 'ซุปเปอร์โหด', 'ด่านยากรออยู่', 'ความท้าทายใหม่รอคุณอยู่'] as const

type Reward = { items: { itemKey: string; quantity: number }[]; adBonusQuantity: number; canWatchAd?: boolean }
export type DuelSettlement = { duels?: { duel: number; stake: number; playerStake?: number; opponentStake?: number; pot?: number; playerScore: number; opponentScore: number; grossPayout?: number; playerTokens: number; opponentTokens: number; fee?: number; playerNet: number }[]; playerExchangeFees?: number; finalProfit?: number; tokenChange?: number; latestTokenBalance?: number }
type Props = { level: number; leagueName?: string; playerScore: number; opponentScore: number; streak: number; longestStreak?: number; comboCount?: number; level250Unlocked: boolean; playerWon: boolean; openChallengePassed?: boolean; duelSettlement?: DuelSettlement; latestTokenBalance?: number; reward?: Reward; rewardEligible?: boolean; rewardClaimed?: boolean; claimingReward?: boolean; watchingAd?: boolean; competition?: { rank?: number; items?: string[]; awarded?: boolean }; elapsedMs?: number; personalBestMs?: number; onClaimReward?: () => void; onWatchAd?: () => void; onRanking?: () => void; onNext: () => void }

const formatTime = (ms?: number) => { const total = Math.max(0, Math.floor((ms ?? 0) / 1000)); return `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}` }

/** Authoritative Tier D settlement presentation. The lotus WebP replaces the retired league-trophy art. */
export function TierDSoloResult({ level, leagueName, playerScore, opponentScore, streak, comboCount = 0, playerWon, openChallengePassed = true, duelSettlement, latestTokenBalance, reward, rewardEligible = false, rewardClaimed = false, claimingReward = false, watchingAd = false, elapsedMs, onClaimReward, onWatchAd, onRanking, onNext }: Props) {
  const [praise] = useState(() => PRAISES[Math.floor(Math.random() * PRAISES.length)])
  const [nextLevelMessage] = useState(() => NEXT_LEVEL_MESSAGES[Math.floor(Math.random() * NEXT_LEVEL_MESSAGES.length)])
  const [nextLevelDifficulty] = useState(() => NEXT_LEVEL_DIFFICULTIES[Math.floor(Math.random() * NEXT_LEVEL_DIFFICULTIES.length)])
  const praiseMotion = useRef(new Animated.Value(0)).current
  const detailsMotion = useRef(new Animated.Value(0)).current
  const actionMotion = useRef(new Animated.Value(0)).current
  useEffect(() => {
    if (!playerWon) return
    const animation = Animated.sequence([Animated.delay(140), Animated.timing(praiseMotion, { toValue: 1, duration: 280, useNativeDriver: true }), Animated.parallel([Animated.timing(detailsMotion, { toValue: 1, duration: 300, useNativeDriver: true }), Animated.timing(actionMotion, { toValue: 1, duration: 340, useNativeDriver: true })])])
    animation.start()
    return () => animation.stop()
  }, [actionMotion, detailsMotion, playerWon, praiseMotion])

  if (!playerWon) return <View style={s.lossPanel}><Text style={s.lossTitle}>LEVEL {level} REMAINS</Text><Text style={s.lossScore}>YOU {playerScore} — {opponentScore} HIGHEST AI</Text>{duelSettlement?<DuelSettlementBreakdown value={duelSettlement}/>:null}{!openChallengePassed ? <Text style={s.lossHint}>OPEN CHALLENGE FAILED · G1+G2+G3 SWEEP REQUIRED</Text> : null}{onRanking ? <GameActionButton size="small" variant="secondary" animation="none" label="LEAGUE TOP 20" onPress={onRanking} /> : null}<GameActionButton label="TRY AGAIN" onPress={onNext} /></View>

  const mustClaim = rewardEligible && !rewardClaimed
  const decadeStart = Math.floor(level / 10) * 10
  const nextMilestone = decadeStart + 10
  const decadeProgress = level === decadeStart ? 0 : level - decadeStart
  const claimLabel = watchingAd ? 'VERIFYING AD…' : claimingReward ? 'PREPARING REWARD…' : reward?.canWatchAd ? 'WATCH AD TO CLAIM REWARDS' : 'COLLECT REWARDS'
  const claim = reward?.canWatchAd ? (onWatchAd ?? onNext) : (onClaimReward ?? onNext)
  const appear = (value: Animated.Value, offset = 10) => ({ opacity: value, transform: [{ translateY: value.interpolate({ inputRange: [0, 1], outputRange: [offset, 0] }) }] })

  return <View style={s.screen} accessibilityLiveRegion="polite">
    <View style={s.hero}>{leagueName ? <Text style={s.leagueHeading}>{leagueName}</Text> : null}<Text style={s.levelHeading}>Lv. {level}</Text><ExpoImage source={LOTUS_VICTORY} contentFit="contain" autoplay style={s.lotus} /><Animated.Text style={[s.praise, { opacity: praiseMotion, transform: [{ scale: praiseMotion.interpolate({ inputRange: [0, 1], outputRange: [.86, 1] }) }] }]}>{praise}</Animated.Text><View style={s.titleRow}><View style={s.ornament} /><Text style={s.clearTitle}>LEVEL CLEARED!</Text><View style={s.ornament} /></View></View>
    <Animated.View style={[s.details, appear(detailsMotion)]}><View style={s.stats}><Stat icon="★" label="SCORE" value={playerScore.toLocaleString('en-US')} /><View style={s.separator} /><Stat icon="♨" label="STREAK" value={`x${streak}`} /><View style={s.separator} /><Stat icon="◷" label="TIME" value={formatTime(elapsedMs)} /></View>{duelSettlement&&Number.isFinite(latestTokenBalance)?<View style={s.tokenBalance}><Text style={s.tokenBalanceLabel}>TOKEN BALANCE</Text><Text style={s.tokenBalanceValue}>{latestTokenBalance!.toLocaleString('en-US')}</Text></View>:null}<Text style={s.nextLevelMessage}>{nextLevelMessage}</Text><DecadeProgress level={level} target={nextMilestone} completed={decadeProgress} />{rewardEligible ? <RewardPreview items={(reward?.items ?? []).slice(0, 2)} claimed={rewardClaimed} /> : null}</Animated.View>
    <Animated.View style={[s.action, appear(actionMotion)]}>{onRanking?<GameActionButton size="small" variant="secondary" animation="none" label="LEAGUE TOP 20" onPress={onRanking}/>:null}{mustClaim ? <GameActionButton disabled={claimingReward || watchingAd} icon={reward?.canWatchAd ? <AdWatchIcon /> : undefined} accessibilityLabel={reward?.canWatchAd ? 'Watch an ad to claim rewards' : 'Collect rewards'} label={claimLabel} variant={reward?.canWatchAd ? 'prestige' : 'primary'} onPress={claim} style={s.claimButton} /> : null}<View style={[s.nextLevelAction, mustClaim && s.nextLevelActionFull]}><GameActionButton multiline labelStyle={{fontSize:15}} label={`Lv. ${level + 1}\n${nextLevelDifficulty}`} onPress={onNext} style={mustClaim ? s.claimButton : undefined} /></View></Animated.View>
  </View>
}

function Stat({ icon, label, value }: { icon: string; label: string; value: string }) { return <View style={s.stat}><Text style={s.statIcon}>{icon}</Text><Text style={s.statLabel}>{label}</Text><Text style={s.statValue}>{value}</Text></View> }
export function DuelSettlementBreakdown({value,compact=false}:{value:DuelSettlement;compact?:boolean}){const rows=Array.isArray(value.duels)?value.duels:[];const profit=Number.isFinite(value.finalProfit)?value.finalProfit!:Number.isFinite(value.tokenChange)?value.tokenChange!:0;const signed=(amount:number)=>`${amount>=0?'+':''}${amount.toLocaleString('en-US')}`;return <View style={[s.duelSettlement,compact&&s.duelSettlementCompact]}><Text style={[s.duelSettlementTitle,compact&&s.duelSettlementTitleCompact]}>TOKEN SETTLEMENT</Text>{rows.length?rows.map(row=>{const playerStake=row.playerStake??row.stake;const aiStake=row.opponentStake??row.stake;const gross=row.grossPayout??row.playerTokens;const lineStyle=[s.duelSettlementLine,compact&&s.duelSettlementLineCompact];return compact?<View key={row.duel} style={s.duelSettlementCompactRow}><Text style={lineStyle}>D{row.duel} · P STAKE {playerStake} · AI STAKE {aiStake} · SCORE {row.playerScore}:{row.opponentScore}</Text><Text style={lineStyle}>GROSS {gross} · NET {signed(row.playerNet)}</Text></View>:<Text key={row.duel} style={lineStyle}>D{row.duel} · P STAKE {playerStake} · AI STAKE {aiStake} · SCORE {row.playerScore}:{row.opponentScore} · GROSS {gross} · NET {signed(row.playerNet)}</Text>}):<Text style={[s.duelSettlementLine,compact&&s.duelSettlementLineCompact]}>DETAILED DUEL BREAKDOWN UNAVAILABLE FOR THIS SESSION</Text>}<Text style={[s.duelSettlementTotal,compact&&s.duelSettlementTotalCompact,profit<=0&&{color:'#ff9d9d'}]}>FINAL PROFIT · {signed(profit)} TOKEN</Text></View>}
function DecadeProgress({ level, target, completed }: { level: number; target: number; completed: number }) { return <View style={s.progressRow}><Text style={s.levelText}>Lv. {level}</Text><View style={s.progressSteps}>{Array.from({ length: 10 }, (_, index) => <View key={index} style={[s.progressStep, index < completed && s.progressStepComplete]} />)}</View><GiftIcon /><Text style={s.levelText}>Lv. {target}</Text></View> }
function GiftIcon() { return <Svg width={20} height={20} viewBox="0 0 24 24" accessibilityLabel="Next ten-level reward"><Rect x="3" y="9" width="18" height="11" rx="1.5" fill="none" stroke="#F3C65C" strokeWidth="1.7"/><Path d="M12 9v11M3 12.5h18M12 9H7.7C5.3 9 5.1 5.7 7.3 5.7c2.3 0 4.7 3.3 4.7 3.3Zm0 0h4.3c2.4 0 2.6-3.3.4-3.3C14.6 5.7 12 9 12 9Z" fill="none" stroke="#FDE19A" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></Svg> }
function AdWatchIcon() { return <Svg width={21} height={21} viewBox="0 0 24 24" accessibilityLabel="Watch ad"><Rect x="2.5" y="5" width="19" height="14" rx="2.2" fill="none" stroke="#FDE19A" strokeWidth="1.7"/><Path d="m10 9 5 3-5 3V9ZM5.5 5v14M18.5 5v14" fill="none" stroke="#FDE19A" strokeWidth="1.45" strokeLinecap="round" strokeLinejoin="round"/></Svg> }
function RewardPreview({ items, claimed }: { items: Reward['items']; claimed: boolean }) { return <View style={s.rewards}><Text style={s.rewardHeading}>{claimed ? 'REWARDS RECEIVED' : 'LEVEL REWARDS'}</Text><View style={s.rewardRow}>{items.map(item => <View key={item.itemKey} style={[s.rewardCard, item.itemKey === 'undo' && s.rareReward]}><Text style={s.rewardIcon}>{item.itemKey === 'undo' ? '✦' : '◆'}</Text><Text style={s.rewardName}>{item.itemKey.replaceAll('_', ' ').toUpperCase()}</Text><Text style={s.rewardAmount}>×{item.quantity}</Text>{item.itemKey === 'undo' ? <Text style={s.rareLabel}>RARE</Text> : null}</View>)}</View></View> }

const s = StyleSheet.create({
  screen: { flex: 1, width: '100%', alignSelf: 'center', justifyContent: 'space-between', maxWidth: 480, paddingBottom: 4 }, hero: { alignItems: 'center', width: '100%', paddingTop: '20%' }, leagueHeading: { color: '#E7C675', fontFamily: 'Cinzel_700Bold', fontSize: 13, letterSpacing: 1.1, marginBottom: 3 }, levelHeading: { alignSelf: 'center', color: '#FFF0C7', fontFamily: 'Cinzel_700Bold', fontSize: 21, letterSpacing: 1.15, textShadowColor: 'rgba(202,145,34,.45)', textShadowRadius: 7 }, lotus: { alignSelf: 'stretch', width: '100%', height: 208 }, praise: { marginTop: -3, color: '#F5A33E', fontSize: 40, lineHeight: 48, fontFamily: Platform.select({ ios: 'Snell Roundhand', android: 'cursive', default: 'cursive' }), fontStyle: 'italic', fontWeight: '800', textAlign: 'center', textShadowColor: 'rgba(222,111,10,.82)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 11 }, titleRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: -5 }, ornament: { width: 31, height: 1, backgroundColor: 'rgba(223,181,93,.72)' }, clearTitle: { color: '#FFF0C7', fontFamily: 'Cinzel_700Bold', fontSize: 21, letterSpacing: 1.15, textShadowColor: 'rgba(202,145,34,.45)', textShadowRadius: 7 },
  details: { width: '100%', marginTop: 28, paddingHorizontal: 20 }, stats: { flexDirection: 'row', alignItems: 'stretch', justifyContent: 'center', paddingHorizontal: 4 }, stat: { flex: 1, alignItems: 'center', gap: 2 }, statIcon: { color: '#F5C45B', fontSize: 25, lineHeight: 28, textShadowColor: 'rgba(255,196,59,.6)', textShadowRadius: 8 }, statLabel: { color: '#D7BF86', fontFamily: 'Cinzel_700Bold', fontSize: 11, letterSpacing: .45 }, statValue: { color: '#FFD979', fontFamily: 'Cinzel_700Bold', fontSize: 27, textShadowColor: 'rgba(197,121,11,.55)', textShadowRadius: 7 }, separator: { width: StyleSheet.hairlineWidth, backgroundColor: 'rgba(214,174,87,.62)', marginVertical: 8 }, nextLevelMessage: { color: '#E8D7A4', fontSize: 13, fontWeight: '700', textAlign: 'center', marginTop: 15, textShadowColor: 'rgba(103,61,7,.72)', textShadowRadius: 5 }, progressRow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 8 }, levelText: { color: '#F7E1A8', fontFamily: 'Cinzel_700Bold', fontSize: 13 }, progressSteps: { flex: 1, flexDirection: 'row', gap: 3, alignItems: 'center' }, progressStep: { flex: 1, height: 5, borderRadius: 3, backgroundColor: 'rgba(149,116,49,.45)', borderWidth: StyleSheet.hairlineWidth, borderColor: 'rgba(238,193,83,.45)' }, progressStepComplete: { backgroundColor: '#E7A82D', borderColor: '#FFE28A', shadowColor: '#FFDA74', shadowOpacity: .8, shadowRadius: 5 },
  duelSettlement:{width:'100%',marginTop:12,padding:10,borderRadius:10,borderWidth:1,borderColor:'rgba(231,198,117,.55)',backgroundColor:'rgba(12,25,18,.78)',gap:3},duelSettlementCompact:{marginTop:0,paddingHorizontal:8,paddingVertical:6,borderRadius:9,gap:1},duelSettlementCompactRow:{paddingVertical:1,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'rgba(231,198,117,.18)'},duelSettlementTitle:{color:'#FFD979',fontFamily:'Cinzel_700Bold',fontSize:11,textAlign:'center',letterSpacing:.7},duelSettlementTitleCompact:{fontSize:9,lineHeight:11},duelSettlementLine:{color:'#E8D7A4',fontSize:9,fontWeight:'700',textAlign:'center'},duelSettlementLineCompact:{fontSize:8,lineHeight:10},duelSettlementTotal:{color:'#8DFFB5',fontFamily:'Cinzel_700Bold',fontSize:14,textAlign:'center',marginTop:4},duelSettlementTotalCompact:{fontSize:11,lineHeight:13,marginTop:1},tokenBalance:{alignSelf:'center',minWidth:220,marginTop:17,paddingHorizontal:18,paddingVertical:9,borderRadius:12,borderWidth:1,borderColor:'#E7C675',backgroundColor:'rgba(30,43,25,.84)',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10},tokenBalanceLabel:{color:'#D7BF86',fontFamily:'Cinzel_700Bold',fontSize:11,letterSpacing:.7},tokenBalanceValue:{color:'#FFD979',fontFamily:'Cinzel_700Bold',fontSize:20,textShadowColor:'rgba(197,121,11,.55)',textShadowRadius:7},
  rewards: { marginTop: 17, alignItems: 'center' }, rewardHeading: { color: '#E7C675', fontFamily: 'Cinzel_700Bold', fontSize: 11, letterSpacing: 1 }, rewardRow: { flexDirection: 'row', justifyContent: 'center', gap: 10, marginTop: 7 }, rewardCard: { width: 112, minHeight: 70, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(215,169,77,.65)', borderRadius: 10, backgroundColor: 'rgba(36,27,12,.72)' }, rareReward: { borderColor: '#FFE28C', backgroundColor: 'rgba(114,69,15,.5)', shadowColor: '#F5C45B', shadowOpacity: .6, shadowRadius: 8, elevation: 4 }, rewardIcon: { color: '#FFD979', fontSize: 17 }, rewardName: { color: '#FFF1C6', fontFamily: 'JetBrainsMono_600SemiBold', fontSize: 8, marginTop: 2 }, rewardAmount: { color: '#F4C45D', fontFamily: 'Cinzel_700Bold', fontSize: 15 }, rareLabel: { position: 'absolute', top: 3, right: 5, color: '#FFF1B4', fontSize: 6, fontWeight: '900', letterSpacing: .5 }, action: { width: '100%', alignItems: 'center', gap: 10, marginTop: 'auto', marginBottom: 54 }, nextLevelAction: { alignItems: 'center' }, nextLevelActionFull: { width: '100%' }, claimButton: { width: '100%' }, lossPanel: { width: '100%', alignItems: 'center', gap: 14, padding: 20, borderRadius: 16, backgroundColor: 'rgba(12,35,23,.97)' }, lossTitle: { color: '#FFD76A', fontFamily: 'Cinzel_700Bold', fontSize: 23 }, lossScore: { color: '#F5F2E8', fontWeight: '800' }, lossHint: { color: '#ffb0b0', fontSize: 11, fontWeight: '800', textAlign: 'center' },
})
