import React, { useEffect, useState } from 'react'
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from 'react-native'
import { router } from 'expo-router'

type Board = 'pb'|'streak'
type League = 'all'|'bronze'|'silver'|'gold'|'platinum'|'diamond'|'elite'|'master'|'grandmaster'|'legend'|'mythic'
type Entry = {rank:number;userId:string;displayName:string;level?:number;elapsedMs?:number;achievedAt?:string;streak?:number}
const leagues:League[]=['all','bronze','silver','gold','platinum','diamond','elite','master','grandmaster','legend','mythic']
const formatTime=(ms?:number)=>ms===undefined?'—':`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`

export function TierDRecordsBoard({serverUrl,accessToken,board,onClose}:{serverUrl:string;accessToken:string;board:Board;onClose:()=>void}){
 const [league,setLeague]=useState<League>('all');const [entries,setEntries]=useState<Entry[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 useEffect(()=>{let active=true;setLoading(true);setError('');fetch(`${serverUrl}/tier-d/records?board=${board}&league=${board==='pb'?league:'all'}`,{headers:{Authorization:`Bearer ${accessToken}`}}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error??'Could not load records');return body}).then(data=>{if(active)setEntries(data.entries??[])}).catch(e=>active&&setError(e instanceof Error?e.message:'Could not load records')).finally(()=>active&&setLoading(false));return()=>{active=false}},[accessToken,board,league,serverUrl])
 return <View style={s.screen}><View style={s.panel}><Pressable style={s.close} onPress={onClose}><Text style={s.closeText}>CLOSE</Text></Pressable><Text style={s.title}>{board==='pb'?'PERSONAL BEST · TOP 50':'LONGEST STREAK · TOP 50'}</Text><Text style={s.sub}>{board==='pb'?'FASTEST LEVEL CLEAR · ALL TIME':'ALL-TIME CONSECUTIVE LEVEL WINS'}</Text>{board==='pb'?<FlatList horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs} data={leagues} keyExtractor={x=>x} renderItem={({item})=><Pressable style={[s.tab,league===item&&s.tabActive]} onPress={()=>setLeague(item)}><Text style={[s.tabText,league===item&&s.tabTextActive]}>{item.toUpperCase()}</Text></Pressable>}/>:null}{loading?<View style={s.state}><ActivityIndicator color="#FFD76A"/></View>:error?<Text style={s.error}>{error}</Text>:<FlatList data={entries} keyExtractor={x=>x.userId} ListEmptyComponent={<Text style={s.empty}>NO RECORDS YET</Text>} renderItem={({item})=><Pressable style={s.row} onPress={()=>router.push({pathname:'/(home)/player/[userId]',params:{userId:item.userId}})}><Text style={s.rank}>#{item.rank}</Text><View style={s.nameBox}><Text numberOfLines={1} style={s.name}>{item.displayName}</Text><Text style={s.detail}>{board==='pb'?`LV. ${item.level} · ${item.achievedAt?new Date(item.achievedAt).toLocaleString():''}`:'ALL TIME'}</Text></View><Text style={s.value}>{board==='pb'?formatTime(item.elapsedMs):`${item.streak} WINS`}</Text></Pressable>}/>}</View></View>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#07150d',padding:14,justifyContent:'center'},panel:{width:'100%',maxWidth:560,maxHeight:'92%',alignSelf:'center',backgroundColor:'#102d1d',borderWidth:1.5,borderColor:'#FFD76A',borderRadius:16,padding:14},close:{position:'absolute',right:12,top:12,zIndex:2,padding:8,borderWidth:1,borderColor:'#FFD76A',borderRadius:8},closeText:{color:'#FFD76A',fontSize:9,fontWeight:'900'},title:{color:'#FFD76A',fontSize:18,fontWeight:'900',textAlign:'center',paddingTop:4},sub:{color:'#9ddaff',fontSize:9,fontWeight:'800',textAlign:'center',marginTop:4},tabs:{gap:5,paddingVertical:12},tab:{borderWidth:1,borderColor:'#426a55',borderRadius:8,paddingHorizontal:8,paddingVertical:5},tabActive:{borderColor:'#FFD76A',backgroundColor:'rgba(255,215,106,.14)'},tabText:{color:'#a9d5bf',fontSize:8,fontWeight:'900'},tabTextActive:{color:'#FFD76A'},state:{height:190,alignItems:'center',justifyContent:'center'},error:{color:'#ff9d9d',textAlign:'center',padding:30},empty:{color:'#a9d5bf',textAlign:'center',padding:30},row:{flexDirection:'row',alignItems:'center',gap:8,padding:9,borderBottomWidth:1,borderColor:'rgba(255,215,106,.18)'},rank:{width:34,color:'#FFD76A',fontWeight:'900'},nameBox:{flex:1},name:{color:'#F5F2E8',fontWeight:'900',fontSize:12},detail:{color:'#a9d5bf',fontSize:8,marginTop:2},value:{color:'#8DFFB5',fontWeight:'900',fontSize:11}})
