import { adMode, productionInterstitialUnitId, productionRewardedUnitId, type RewardedContext } from './adConfig'
import type { AdResult, ClientAdProvider } from './adProvider.types'

// Expo Go lacks RNGoogleMobileAdsModule. A guarded require prevents that old
// binary from crashing the router; a rebuilt development client resolves it.
let googleAds:any
try { googleAds=require('react-native-google-mobile-ads') } catch { googleAds=undefined }
const rewardedUnit=()=>adMode==='google_test'?googleAds?.TestIds?.REWARDED:productionRewardedUnitId
const interstitialUnit=()=>adMode==='google_test'?googleAds?.TestIds?.INTERSTITIAL:productionInterstitialUnitId

class GoogleMobileAdsProvider implements ClientAdProvider {
 readonly mode=adMode;private initialized=false;private initializing:Promise<void>|undefined;private rewarded:any;private interstitial:any;private rewardedReady=false;private interstitialReady=false
 async initialize(){if(this.initialized)return;if(!this.initializing)this.initializing=(async()=>{if(adMode!=='google_test'&&!(adMode==='production'&&productionRewardedUnitId&&productionInterstitialUnitId))return;try{if(!googleAds)throw new Error('Google Mobile Ads native module is not installed in this binary');await googleAds.default().initialize();this.initialized=true;console.info(`[ads] initialized mode=${adMode}`)}catch(error){console.warn('[ads] Google Mobile Ads initialization failed',error);throw error}})();return this.initializing}
 async preloadRewarded(_context?:RewardedContext){try{await this.initialize()}catch{return}const unit=rewardedUnit();if(!this.initialized||!unit||this.rewardedReady)return;const ad=googleAds.RewardedAd.createForAdRequest(unit,{requestNonPersonalizedAdsOnly:true});this.rewarded=ad;ad.addAdEventListener(googleAds.RewardedAdEventType.LOADED,()=>{this.rewardedReady=true});ad.addAdEventListener(googleAds.AdEventType.ERROR,()=>{this.rewardedReady=false;this.rewarded=undefined});ad.load()}
 async preloadInterstitial(){try{await this.initialize()}catch{return}const unit=interstitialUnit();if(!this.initialized||!unit||this.interstitialReady)return;const ad=googleAds.InterstitialAd.createForAdRequest(unit,{requestNonPersonalizedAdsOnly:true});this.interstitial=ad;ad.addAdEventListener(googleAds.AdEventType.LOADED,()=>{this.interstitialReady=true});ad.addAdEventListener(googleAds.AdEventType.ERROR,()=>{this.interstitialReady=false;this.interstitial=undefined});ad.load()}
 async showRewarded(context:RewardedContext):Promise<AdResult>{const ad=this.rewarded;if(!ad||!this.rewardedReady){void this.preloadRewarded(context);return{shown:false,earned:false,reason:'not_ready'}}this.rewarded=undefined;this.rewardedReady=false;return new Promise(resolve=>{let earned=false,done=false;const finish=(x:AdResult)=>{if(done)return;done=true;offEarned();offClosed();offError();void this.preloadRewarded(context);resolve(x)};const offEarned=ad.addAdEventListener(googleAds.RewardedAdEventType.EARNED_REWARD,()=>{earned=true});const offClosed=ad.addAdEventListener(googleAds.AdEventType.CLOSED,()=>finish({shown:true,earned,reason:earned?undefined:'closed_without_reward'}));const offError=ad.addAdEventListener(googleAds.AdEventType.ERROR,()=>finish({shown:true,earned:false,reason:'show_failed'}));ad.show().catch(()=>finish({shown:false,earned:false,reason:'show_failed'}))})}
 async showInterstitial():Promise<AdResult>{const ad=this.interstitial;if(!ad||!this.interstitialReady){void this.preloadInterstitial();return{shown:false,earned:false,reason:'not_ready'}}this.interstitial=undefined;this.interstitialReady=false;return new Promise(resolve=>{let done=false;const finish=(x:AdResult)=>{if(done)return;done=true;offClosed();offError();void this.preloadInterstitial();resolve(x)};const offClosed=ad.addAdEventListener(googleAds.AdEventType.CLOSED,()=>finish({shown:true,earned:false}));const offError=ad.addAdEventListener(googleAds.AdEventType.ERROR,()=>finish({shown:true,earned:false,reason:'show_failed'}));ad.show().catch(()=>finish({shown:false,earned:false,reason:'show_failed'}))})}
}
export const adProvider:ClientAdProvider=new GoogleMobileAdsProvider()
