import { AccessibilityInfo, Animated, Image, Pressable, StyleProp, StyleSheet, Text, TextStyle, View, ViewStyle } from 'react-native'
import { useEffect, useMemo, useRef, useState } from 'react'
import { ACTION_BUTTON_IMAGES, ActionButtonName } from '../../ui/buttonManifest'
import { UI_THEME } from '../../ui/theme'

type Props={icon:ActionButtonName;label:string;onPress:()=>void;disabled?:boolean;variant?:'normal'|'waiting'|'disabled';style?:StyleProp<ViewStyle>;textStyle?:StyleProp<TextStyle>;sparkleEnabled?:boolean;shimmerEnabled?:boolean;breathingEnabled?:boolean}
type Spark={left:`${number}%`;top:`${number}%`;size:number}
export function AnimatedCTAButton({icon,label,onPress,disabled,variant='normal',style,textStyle,sparkleEnabled=true,shimmerEnabled=true,breathingEnabled=true}:Props){
 const inactive=!!disabled||variant!=='normal',scale=useRef(new Animated.Value(1)).current,shimmer=useRef(new Animated.Value(-1)).current,spark=useRef(new Animated.Value(0)).current
 const [reduce,setReduce]=useState(false),[stars,setStars]=useState<Spark[]>([])
 const seed=useMemo(()=>Math.random()*1800,[])
 useEffect(()=>{let live=true;void AccessibilityInfo.isReduceMotionEnabled().then(value=>live&&setReduce(value));const sub=AccessibilityInfo.addEventListener?.('reduceMotionChanged',setReduce);return()=>{live=false;sub?.remove?.()}},[])
 useEffect(()=>{if(inactive||reduce)return;let sparkleTimer:ReturnType<typeof setTimeout>,shimmerTimer:ReturnType<typeof setTimeout>;let stopped=false
  const sparkleCycle=()=>{if(stopped)return;setStars(Array.from({length:1+Math.floor(Math.random()*3)},()=>({left:`${8+Math.random()*84}%` as `${number}%`,top:`${18+Math.random()*58}%` as `${number}%`,size:3+Math.random()*3})));spark.setValue(0);Animated.sequence([Animated.timing(spark,{toValue:1,duration:180,useNativeDriver:true}),Animated.timing(spark,{toValue:0,duration:850+Math.random()*450,useNativeDriver:true})]).start();sparkleTimer=setTimeout(sparkleCycle,2000+Math.random()*3000)}
  const shimmerCycle=()=>{if(stopped)return;shimmer.setValue(-1);Animated.timing(shimmer,{toValue:1,duration:650,useNativeDriver:true}).start();shimmerTimer=setTimeout(shimmerCycle,4000+Math.random()*4000)}
  sparkleTimer=setTimeout(sparkleCycle,seed);shimmerTimer=setTimeout(shimmerCycle,seed+900);return()=>{stopped=true;clearTimeout(sparkleTimer);clearTimeout(shimmerTimer);spark.stopAnimation();shimmer.stopAnimation()}},[inactive,reduce,seed,spark,shimmer])
 useEffect(()=>{if(inactive||reduce||!breathingEnabled){scale.setValue(1);return}const loop=Animated.loop(Animated.sequence([Animated.timing(scale,{toValue:1.01,duration:1500,useNativeDriver:true}),Animated.timing(scale,{toValue:1,duration:1500,useNativeDriver:true})]));loop.start();return()=>loop.stop()},[inactive,reduce,breathingEnabled,scale])
 const press=()=>{if(inactive)return;Animated.sequence([Animated.timing(scale,{toValue:.965,duration:85,useNativeDriver:true}),Animated.timing(scale,{toValue:1,duration:110,useNativeDriver:true})]).start();onPress()}
 return <Animated.View style={[styles.wrap,{transform:[{scale}]}]}><Pressable onPress={press} disabled={inactive} style={[styles.button,style,inactive&&styles.disabled]}><Image source={ACTION_BUTTON_IMAGES[icon]} style={styles.image} resizeMode="contain"/>{!inactive&&!reduce&&shimmerEnabled?<Animated.View pointerEvents="none" style={[styles.shimmer,{transform:[{translateX:shimmer.interpolate({inputRange:[-1,1],outputRange:[-160,160]})}]}]}/>:null}{!inactive&&!reduce&&sparkleEnabled?<View pointerEvents="none" style={styles.fx}>{stars.map((star,i)=><Animated.View key={`${i}-${star.left}`} style={[styles.star,{left:star.left,top:star.top,width:star.size,height:star.size,opacity:spark,transform:[{scale:spark.interpolate({inputRange:[0,1],outputRange:[.5,1.5]})}]}]}/>)}</View>:null}<View pointerEvents="none" style={styles.labelSlot}><Text style={[styles.label,textStyle]} numberOfLines={3}>{variant==='waiting'?'Waiting…':label}</Text></View></Pressable></Animated.View>
}
const styles=StyleSheet.create({wrap:{width:'100%',aspectRatio:1.5},button:{width:'100%',height:'100%',alignItems:'center',justifyContent:'center',overflow:'hidden'},disabled:{opacity:.52},image:{width:'100%',height:'100%'},labelSlot:{...StyleSheet.absoluteFill,alignItems:'center',justifyContent:'center'},label:{fontFamily:UI_THEME.fonts.headingBold,color:UI_THEME.gold.primary,fontSize:16,textAlign:'center',textShadowColor:'rgba(0,0,0,.8)',textShadowOffset:{width:0,height:1},textShadowRadius:3},fx:{...StyleSheet.absoluteFill,overflow:'hidden'},star:{position:'absolute',backgroundColor:'#FFF6C8',borderRadius:8,shadowColor:'#FFD76A',shadowOpacity:.9,shadowRadius:5,elevation:2},shimmer:{position:'absolute',width:44,height:'180%',backgroundColor:'rgba(255,245,190,.16)',transform:[{rotate:'18deg'}]}})
